module.exports = {
    internalId             : "IFLE03",
    formulas : {
        yr                          : "yr__01",
        proposalStartDate           : "proposalStartDate__01",
        jobClass                    : "jobClass__01",
        ageMethod                   : "ageMethod__01",
        maxT                        : "coverageTerm__01",
        coverageTerm                : "coverageTerm__01",
        coverageEndAge              : "maturityAge__01",
        premium                     : "ilpPremium__10",
        maturityAge                 : "maturityAge__01",
        ageAtT                      : "ageAtT__01",
        entryAge                    : "entryAge__01",
        phEntryAge                  : "phEntryAge__01",
        totalLoadings               : "totalLoadings__01",
        saCalculated                : "saCalculated__04",
        annualPremium               : "ilpAnnualPremium__10",
        halfYearlyPremium           : "halfYearlyPremium__02",
        quarterlyPremium            : "quarterlyPremium__02",
        monthlyPremium              : "monthlyPremium__02",
        annualPremiumAtT            : "zero",
        totalPremiumPaidAtT         : "zero",
        totalPremium                : "zero",
        polAnnualPremiumAtT         : "zero",
        polTotalPremiumPaidAtT      : "zero",
        polFeeAtT                   : "polFeeAtT__01",
        polFeeAfterModalFactor      : "zero",
        polFeeBeforeModalFactor     : "zero",
        deathBenefit                : "zero",
        deathBenefitGtd             : "zero",
        totalDeathBenefitGtd        : "zero",
        deathBenefitNonGtdAtT       : "zero",
        deathBenefitLowAtT          : ["deathBenefitLowAtT__10", "roundThousandHalfUp"],
        deathBenefitMidAtT          : ["deathBenefitMidAtT__10", "roundThousandHalfUp"],
        deathBenefitHighAtT         : ["deathBenefitHighAtT__10", "roundThousandHalfUp"],
        deathBenefitGtdAtT          : "deathBenefitGtdAtT__10",
        totalDeathBenefitAtT        : "zero",
        totalSurrenderValueAtT      : "zero",
        terminalBonusAtT            : "zero",
        cashBonusAtT                : "zero",
        accumCashBonusAtT           : "zero",
        revBonusAtT                 : "zero",
        accumRevBonusAtT            : "zero",
        survivalBenefitGtd          : "zero",
        accumSurvivalBenefitAtT     : "zero",
        accumSurvivalBenefitRate    : "zero",
        surrenderValueGtdAtT        : "zero",
        maturityBenefitGtd          : "zero",
        totalDistributionCost       : "zero",
        // ILP specific
        costOfInsuranceAtT          : "costOfInsuranceAtT__01",
        costOfInsurance             : "costOfInsurance__01",
        monthlyCostOfInsurance      : "monthlyCostOfInsurance__01",
        costOfRidersAtT             : "zero",
        totalCostOfRidersAtT        : "totalCostOfRidersAtT__01",
        accumCostOfRidersAtT        : "accumCostOfRidersAtT__01",
        basicCostAtT                : "basicCostAtT__01",
        tivLowAtT                   : ["tivLowAtT__01", "roundThousandHalfUp"],
        tivMidAtT                   : ["tivMidAtT__01", "roundThousandHalfUp"],
        tivHighAtT                  : ["tivHighAtT__01", "roundThousandHalfUp"],
        tiv                         : "zero",
        adhocTopupAtT               : ["adhocTopupAtT__01", "roundThousandHalfUp"],
        netAdhocTopupAtT            : "netAdhocTopupAtT__01",
        withdrawalAtT               : ["withdrawalAtT__01", "roundThousandHalfUp"],
        netWithdrawalAtT            : "netWithdrawalAtT__01",
        regularTopupAtT             : ["regularTopupAtT__01", "roundThousandHalfUp"],
        netRegularTopupAtT          : ["netRegularTopupAtT__01", "roundThousandHalfUp"],
        targetPremiumAtT            : ["targetPremiumAtT__01", "roundThousandHalfUp"],
        netTargetPremiumAtT         : "netTargetPremiumAtT__01",
        singlePremium               : ["singlePremium__10", "roundThousandHalfUp"],
        singlePremiumModalFactor    : ["singlePremiumModalFactor__10", "roundThousandHalfUp"],
        singlePremiumAtT            : ["singlePremiumAtT__01", "roundThousandHalfUp"],
        netSinglePremiumAtT         : "netSinglePremiumAtT__01",
        accumDebtAtT                : ["accumDebtAtT__01", "roundThousandHalfUp"],
        outstdDebtAtT               : "outstdDebtAtT__01",
        debtAtT                     : "debtAtT__01",
        accumDebtPaidAtT            : ["accumDebtPaidAtT__01", "roundThousandHalfUp"],
        debtRepayAtT                : "debtRepayAtT__01",
        debtAccumPeriod             : "debtAccumPeriod__02",
        debtRepayPeriod             : "debtRepayPeriod__01",
        accumFactor                 : "accumFactor__01",
        monthlyCostOfRiders         : "monthlyCostOfRiders__01",
        macAtT                      : "zero",
    },
    validators              : {
        validateMain                : 'validateMain__02',
        validateAllRiders           : 'validateAllRiders__01',
        validateRider               : 'validateRider__01',
        validateSaLimit             : 'validateSaLimit__01',
        validateAgeLimit            : 'validateAgeLimit__01',
        validatePremiumLimit        : 'validatePremiumLimit__01',
        validateAllFundAllocations  : 'validateAllFundAllocations__01',
        validateFundAllocation      : 'validateFundAllocation__01',
        validateMinFundAllocation   : 'validateMinFundAllocation__01',
        validateTargetPremiumLimit  : 'validateIlpTargetPremiumLimit__01',
        validateRegularTopupLimit   : 'validateIlpRegularTopupLimit__01',
        validateMinRegularTopup     : 'validateIlpMinRegularTopup__01',
        validateTopupLimit          : 'pass',
        validateWithdrawalLimit     : 'pass',
        validateSaMultiple          : 'validateSaMultiple__01',
        validateCoverEndAge         : 'validateCoverAge__01',
        validateAllTopups           : 'validateAllTopups__01',
        validateMinMaxTopupAmounts  : 'validateMinMaxTopupAmounts__01',
        validateAllWithdrawals      : 'validateAllWithdrawals__01',
        validateMinMaxWithdrawal    : 'validateMinMaxWithdrawal__01',
        validateInput               : 'validateInput__01',
        validatePersonProduct       : 'validatePersonProduct__01'

    },
    // input                   : {
    //     backDate            : 'date',
    //     la                  : 'num',
    //     basicSa             : "num",
    //     targetPremium       : "num" ,
    //     regularTopup        : "num",
    //     premiumTerm         : "num",
    //     paymentFrequency    : "str",
    // },
    inputFields  : {
        productId            : 'num',
        productCode          : 'str',
        lifeAssuredNumber    : "num",
        sumAssured           : "num",
        regularTopup         : "num",
        targetPremium        : "num",
        paymentMode          : "str"
    },
    personFields : {
      name : "str",
      gender : "str",
      birthDate : "str",
    },

    calculationFields       : ['entryAge','coverageTerm','annualPremium','premium'],
    illustrationFields      : ['t', 'ageAtT', 'targetPremiumAtT', 'regularTopupAtT',
                               'adhocTopupAtT','withdrawalAtT','tivLowAtT','tivMidAtT', 'tivHighAtT',
                               'deathBenefitLowAtT', 'deathBenefitMidAtT','deathBenefitHighAtT'],
    illustrationColNames    : ['Yr','Age','Target Premium','RTU', 'Topup', 'Withdrawal',
                               'TIV(L)','TIV(M)','TIV(H)','DB(L)','DB(M)','DB(H)'],
    illustrationColWidths   : [5,5,10,10,10,10,10,10,10,10,10,10,10],
    smallViewOptions : [
        { type: 'table', label: 'Topups & Withdrawals' , colIndexes: [0,1,2,3,4,5] },
        { type: 'table', label: 'TIV' ,            colIndexes: [0,1,6,7,8] },
        { type: 'table', label: 'Death Benefit' ,  colIndexes: [0,1,9,10,11] },
        { type: 'chart', label : 'TIV' ,  x: [0], y: [6,7] },
        { type: 'chart', label : 'Death Benefit' ,  x: [0], y: [10,11] },

    ]

}
