module.exports = {
    internalId             : "TEND02",
    formulas : {
        yr                          : "yr__01",
        proposalStartDate           : "proposalStartDate__01",
        jobClass                    : "jobClass__01",
        ageMethod                   : "ageMethod__01",
        maxT                        : "coverageTerm__01",
        coverageTerm                : "coverageTerm__01",
        coverageEndAge              : "zero",
        premium                     : "premium__01",
        maturityAge                 : "maturityAge__02",
        ageAtT                      : "ageAtT__02",
        entryAge                    : "entryAge__01",
        phEntryAge                  : "phEntryAge__01",
        totalLoadings               : "totalLoadings__01",
        saCalculated                : "saCalculated__04",
        annualPremium               : "annualPremium__02",
        halfYearlyPremium           : "halfYearlyPremium__01",
        quarterlyPremium            : "quarterlyPremium__01",
        monthlyPremium              : "monthlyPremium__01",
        annualPremiumAtT            : "annualPremiumAtT__02",
        totalPremiumPaidAtT         : "totalPremiumPaidAtT__01",
        totalPremium                : "totalPremium__01",
        polAnnualPremiumAtT         : ["polAnnualPremiumAtT__01","roundThousandHalfUp"],
        polTotalPremiumPaidAtT      : ["polTotalPremiumPaidAtT__01", "roundThousandHalfUp"],
        polFeeAtT                   : "zero",
        polFeeAfterModalFactor      : "zero",
        polFeeBeforeModalFactor     : "zero",
        deathBenefit                : "zero",
        deathBenefitGtd             : "zero",
        deathBenefitGtdAtT          : ["deathBenefitGtdAtT__01","roundThousandHalfUp"],
        totalDeathBenefitGtd        : "zero",
        deathBenefitNonGtdAtT       : "zero",
        deathBenefitLowAtT          : "zero",
        deathBenefitMidAtT          : "zero",
        deathBenefitHighAtT         : "zero",
        deathBenefitAtT             : "deathBenefitAtT__01",
        totalDeathBenefitAtT        : ["totalDeathBenefitAtT__01", "roundThousandHalfUp"],
        terminalBonusAtT            : "zero",
        cashBonusAtT                : "zero",
        accumCashBonusAtT           : "zero",
        revBonusAtT                 : "zero",
        accumRevBonusAtT            : "zero",
        survivalBenefitGtdAtT       : ["survivalBenefitGtdAtT__01","roundThousandHalfUp"],
        accumSurvivalBenefitAtT     : ["accumSurvivalBenefitAtT__01","roundThousandHalfUp"],
        accumSurvivalBenefitRate    : "accumSurvivalBenefitRate__01",
        surrenderValueGtdAtT        : ["surrenderValueGtdAtT__01", "roundThousandHalfUp"],
        totalSurrenderValueAtT      : ["totalSurrenderValueAtT__01", "roundThousandHalfUp"],
        maturityBenefitGtd          : "zero",
        totalDistributionCost       : "zero",
        // ILP specific
        costOfInsuranceAtT          : "zero",
        costOfInsurance             : "zero",
        monthlyCostOfInsurance      : "zero",
        costOfRidersAtT             : "zero",
        totalCostOfRidersAtT        : "zero",
        accumCostOfRidersAtT        : "zero",
        monthlyCostOfRiders         : "zero",
        basicCostAtT                : "zero",
        tivLowAtT                   : "zero",
        tivMidAtT                   : "zero",
        tivHighAtT                  : "zero",
        tiv                         : "zero",
        topupAtT                    : "zero",
        netTopupAtT                 : "zero",
        withdrawalAtT               : "zero",
        netWithdrawalAtT            : "zero",
        regularTopupAtT             : "zero",
        netRegularTopupAtT          : "zero",
        targetPremiumAtT            : "zero",
        netTargetPremiumAtT         : "zero",
        singlePremium               : "zero",
        singlePremiumModalFactor    : "zero",
        singlePremiumAtT            : "zero",
        netSinglePremiumAtT         : "zero",
        debtAtT                     : "zero",
        outstdDebtAtT               : "zero",
        debtForT                    : "zero",
        debtPaidAtT                 : "zero",
        debtRepayForT               : "zero",
        debtAccumPeriod             : "zero",
        debtRepayPeriod             : "zero",
        accumFactor                 : "zero",
        macAtT                      : "zero",
    },
    validators              : {
        validateMain                : 'validateMain__01',
        validateAllRiders           : 'validateAllRiders__01',
        validateRider               : 'pass',
        validateSaLimit             : 'validateSaLimit__01',
        validateAgeLimit            : 'validateAgeLimit__01',
        validatePremiumLimit        : 'pass',
        validateAllFundAllocations  : 'pass',
        validateFundAllocation      : 'pass',
        validateMinFundAllocation   : 'pass',
        validateTargetPremiumLimit  : 'pass',
        validateRegularTopupLimit   : 'pass',
        validateMinRegularTopup     : 'pass',
        validateTopupLimit          : 'pass',
        validateWithdrawalLimit     : 'pass',
        validateSaMultiple          : 'pass',
        validateMinMaxSaUnits       : 'pass',
        validateCoverageEndAge      : 'pass',
        validateInput               : 'validateInput__01',
        validatePersonProduct       : 'validatePersonProduct__01'

    },
    input                   : {
        la                  : 'num',
        initialSa           : "num",
        backDate            : 'date',
        paymentFrequency    : 'str',
        initialSa           : 'num',
        premiumTerm         : 'num',
        quotationDate       : 'date',

    },
    inputFields  : {
        productId            : 'num',
        productCode          : 'str',
        lifeAssuredNumber    : "num",
        coverageTermType     : "str",
        coverageTermValue    : "num",
        sumAssured           : "num",
        paymentMode          : "str"
    },
    personFields : {
      name : "str",
      gender : "str",
      birthDate : "str",
    },

    calculationFields       : ['entryAge','phEntryAge','coverageTerm','annualPremium','premium'],
    illustrationFields      : ['t', 'ageAtT', 'pol.polAnnualPremiumAtT', 'pol.polTotalPremiumPaidAtT',
                               'survivalBenefitGtdAtT','accumSurvivalBenefitAtT', 'surrenderValueGtdAtT',
                               'totalSurrenderValueAtT','deathBenefitGtdAtT','totalDeathBenefitAtT'],

    illustrationColNames             : ['Yr','Age','Annual Premium','Total Premium Paid', 'SB', 'Accum. SB', 'Surrender','Surrndr+SB','Death','Death+SB'],
    illustrationColWidths            : [4,5,10,12,9,10,12,13,12,12],
    smallViewOptions : [
        { type: 'table', label : 'Premiums & SB' ,  colIndexes: [0,1,2,3,4,5] },
        { type: 'table', label : 'Surrender&Death Ben' ,  colIndexes: [0,1,6,7,8,9] },
        { type: 'chart', label : 'AP vs Surrender+SB' ,  x: [0], y: [3,7] },
        { type: 'chart', label : 'AP vs Death+SB' ,  x: [0], y: [3,9] },

    ]

}
