module.exports={
  "ageLimit": {
    "10001001:2:7:7:3:88:88:0:0:0:0:0:0:0:0:0:N:0:0": [
      10130530, 
      "5", 
      30, 
      60, 
      999, 
      999, 
      999, 
      999, 
      999, 
      "1", 
      0, 
      999, 
      401, 
      "2017-03-17 00:00:00", 
      401, 
      "2017-03-17 00:00:00", 
      "1", 
      18, 
      "1", 
      0, 
      999, 
      0, 
      "2017-03-17 00:00:00", 
      "2017-03-17 00:00:00", 
      "", 
      10130529
    ], 
    "_meta": {
      "_cols": [
        "listId", 
        "minInsdNbAgeUnit", 
        "minInsdNbAge", 
        "maxInsdNbAge", 
        "maxInsdRnAge", 
        "maxInsdNbPuAge", 
        "maxInsdNbExAge", 
        "maxInsdRnExAge", 
        "maxPhNbAge", 
        "minJiNbAgeUnit", 
        "minJiNbAge", 
        "maxJiNbAge", 
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "maxInsdNbAgeUnit", 
        "minPhNbAge", 
        "maxJiNbAgeUnit", 
        "payYearMax", 
        "maxDefermentAge", 
        "minDefermentAge", 
        "insertTimestamp", 
        "updateTimestamp", 
        "benefitLevel", 
        "productVersionId"
      ], 
      "_coltypes": [
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "dtm", 
        "num", 
        "dtm", 
        "str", 
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "dtm", 
        "dtm", 
        "str", 
        "num"
      ], 
      "_key_chargePeriod": [
        [
          "2", 
          "*"
        ]
      ], 
      "_key_chargeType": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_chargeYear": [
        [
          "7", 
          "*"
        ]
      ], 
      "_key_chargeYearMax": [
        [
          "7", 
          "*"
        ]
      ], 
      "_key_coveragePeriod": [
        [
          "3", 
          "*"
        ]
      ], 
      "_key_coverageYear": [
        [
          "88", 
          "*"
        ]
      ], 
      "_key_coverageYearMax": [
        [
          "88", 
          "*"
        ]
      ], 
      "_key_endPeriod": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_endYear": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_endYearMax": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_gender": [
        [
          "N", 
          "*"
        ]
      ], 
      "_key_insuredStatus": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payEnsure": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payPeriod": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payYear": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_key_sa": [
        [
          "0", 
          "1000000000000000"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "num"
        ], 
        [
          "chargePeriod", 
          "str"
        ], 
        [
          "chargeYear", 
          "num"
        ], 
        [
          "chargeYearMax", 
          "num"
        ], 
        [
          "coveragePeriod", 
          "str"
        ], 
        [
          "coverageYear", 
          "num"
        ], 
        [
          "coverageYearMax", 
          "num"
        ], 
        [
          "payPeriod", 
          "str"
        ], 
        [
          "payYear", 
          "num"
        ], 
        [
          "endPeriod", 
          "str"
        ], 
        [
          "endYear", 
          "num"
        ], 
        [
          "endYearMax", 
          "num"
        ], 
        [
          "payEnsure", 
          "num"
        ], 
        [
          "chargeType", 
          "str"
        ], 
        [
          "sa", 
          "num"
        ], 
        [
          "payMode", 
          "num"
        ], 
        [
          "gender", 
          "str"
        ], 
        [
          "insuredStatus", 
          "str"
        ], 
        [
          "specialAuth", 
          "num"
        ]
      ]
    }
  }, 
  "cashBonusRate": {}, 
  "cashValue": {}, 
  "liabilityConfig": {}, 
  "modelFactor": {
    "10001001:*:1:1:*": [
      1
    ], 
    "10001001:*:2:1:*": [
      0.52
    ], 
    "10001001:*:3:1:*": [
      0.27
    ], 
    "10001001:*:4:1:*": [
      0.095
    ], 
    "_meta": {
      "_cols": [
        "chargeRate"
      ], 
      "_coltypes": [
        "num"
      ], 
      "_key_chargeType": [
        [
          "2", 
          "*"
        ], 
        [
          "4", 
          "*"
        ], 
        [
          "3", 
          "*"
        ], 
        [
          "1", 
          "*"
        ]
      ], 
      "_key_masterId": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_modelType": [
        [
          "1", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "masterId", 
          "int"
        ], 
        [
          "chargeType", 
          "str"
        ], 
        [
          "modelType", 
          "int"
        ], 
        [
          "payMode", 
          "int"
        ]
      ]
    }
  }, 
  "payLiability": {}, 
  "premLimit": {
    "10001001:0:0:0:0": [
      10130535, 
      0, 
      1000000000000000, 
      0, 
      1000000000000000, 
      0, 
      0, 
      0, 
      0, 
      401, 
      "2017-03-17 00:00:00", 
      401, 
      "2017-03-17 00:00:00", 
      0, 
      0, 
      30, 
      "2017-03-17 00:00:00", 
      "2017-03-17 00:00:00", 
      10130529, 
      "2", 
      7, 
      1000000000000000, 
      1000000000000000
    ], 
    "_meta": {
      "_cols": [
        "listId", 
        "minInitialPrem", 
        "maxInitialPrem", 
        "minSubseqPrem", 
        "maxSubseqPrem", 
        "minIncremntPrem", 
        "minReguTopupPrem", 
        "minReguTopupIncr", 
        "minAdTopupPrem", 
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "minDecremntPrem", 
        "minReguTopupDecr", 
        "moneyId", 
        "insertTimestamp", 
        "updateTimestamp", 
        "productVersionId", 
        "chargePeriod", 
        "chargeYear", 
        "maxAdTopupPrem", 
        "maxReguTopupPrem"
      ], 
      "_coltypes": [
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "dtm", 
        "num", 
        "dtm", 
        "num", 
        "num", 
        "num", 
        "dtm", 
        "dtm", 
        "num", 
        "str", 
        "num", 
        "num", 
        "num"
      ], 
      "_key_age": [
        [
          "0", 
          "999"
        ]
      ], 
      "_key_chargeType": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "num"
        ], 
        [
          "chargeType", 
          "str"
        ], 
        [
          "age", 
          "num"
        ], 
        [
          "payMode", 
          "num"
        ], 
        [
          "specialAuth", 
          "num"
        ]
      ]
    }
  }, 
  "prodFundPremLimit": {}, 
  "productAllowables": {
    "attachableRiders": [
      [], 
      [
        "num", 
        "str", 
        "str", 
        "str"
      ], 
      [
        "attachId", 
        "attachType", 
        "attachCompulsory", 
        "gender"
      ]
    ], 
    "bonusOptions": [
      [], 
      [
        "str"
      ], 
      [
        "modeId"
      ]
    ], 
    "coverageTerms": [
      [
        [
          "3", 
          88
        ]
      ], 
      [
        "str", 
        "num"
      ], 
      [
        "coveragePeriod", 
        "coverageYear"
      ]
    ], 
    "currencies": [
      [
        [
          30
        ]
      ], 
      [
        "num"
      ], 
      [
        "moneyId"
      ]
    ], 
    "funds": [
      [], 
      [
        "str"
      ], 
      [
        "fundCode"
      ]
    ], 
    "organizations": [
      [
        [
          101
        ]
      ], 
      [
        "num"
      ], 
      [
        "organId"
      ]
    ], 
    "payMethods": [
      [
        [
          "1", 
          "0", 
          1
        ]
      ], 
      [
        "str", 
        "str", 
        "num"
      ], 
      [
        "chargeType", 
        "premSequen", 
        "payMode"
      ]
    ], 
    "paymentFreq": [
      [
        [
          "2"
        ], 
        [
          "4"
        ], 
        [
          "3"
        ], 
        [
          "1"
        ]
      ], 
      [
        "str"
      ], 
      [
        "chargeType"
      ]
    ], 
    "premiumTerms": [
      [
        [
          "2", 
          7
        ]
      ], 
      [
        "str", 
        "num"
      ], 
      [
        "chargePeriod", 
        "chargeYear"
      ]
    ], 
    "qualifications": [
      [], 
      [
        "num"
      ], 
      [
        "testTypeId"
      ]
    ], 
    "strategies": [
      [], 
      [
        "str", 
        "num"
      ], 
      [
        "strategyCode", 
        "tariffType"
      ]
    ], 
    "survivalOptions": [
      [], 
      [
        "str"
      ], 
      [
        "survivalOption"
      ]
    ]
  }, 
  "productChargeList": {}, 
  "productCurrency": {
    "10001001:101:30:2": [
      401, 
      "2017-03-17 00:00:00", 
      401, 
      "2017-03-17 00:00:00", 
      "EBAO2000", 
      "2017-03-17 00:00:00", 
      "2017-03-17 00:00:00"
    ], 
    "_meta": {
      "_cols": [
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "entityFund", 
        "insertTimestamp", 
        "updateTimestamp"
      ], 
      "_coltypes": [
        "num", 
        "dtm", 
        "num", 
        "dtm", 
        "str", 
        "dtm", 
        "dtm"
      ], 
      "_key_entityFundType": [
        [
          "2", 
          "*"
        ]
      ], 
      "_key_moneyId": [
        [
          "30", 
          "*"
        ]
      ], 
      "_key_organId": [
        [
          "101", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "num"
        ], 
        [
          "organId", 
          "num"
        ], 
        [
          "moneyId", 
          "num"
        ], 
        [
          "entityFundType", 
          "str"
        ]
      ]
    }
  }, 
  "productFund": {}, 
  "productLife": {
    "10001001": [
      1, 
      "CRITICAL ILLNESS 88", 
      "CRITICAL ILLNESS 88", 
      "PRIME88CIR", 
      "", 
      "6", 
      "2", 
      "0", 
      "1", 
      "N", 
      "", 
      "2016-08-01 00:00:00", 
      "", 
      0, 
      0, 
      0, 
      0, 
      10000000000000000, 
      "Y", 
      "", 
      "N", 
      "N", 
      "", 
      "17", 
      "0", 
      "0", 
      "0", 
      0, 
      "Y", 
      "", 
      0, 
      "N", 
      "GDFJFGYN", 
      "1", 
      "1", 
      "1", 
      "", 
      "0", 
      "N", 
      "Y", 
      "N", 
      "N", 
      "2017-04-06 00:00:00", 
      401, 
      "1", 
      "N", 
      "", 
      "1", 
      "N", 
      "N", 
      30, 
      "0", 
      "0", 
      "", 
      "1", 
      "4", 
      "N", 
      "N", 
      "N", 
      "N", 
      0, 
      "1", 
      0, 
      0, 
      0, 
      0, 
      0, 
      99, 
      "", 
      "", 
      "N", 
      10000000000000000, 
      "1", 
      "N", 
      "N", 
      "1", 
      "N", 
      "N", 
      "N", 
      "N", 
      "", 
      999, 
      "N", 
      0, 
      "N", 
      "0", 
      "N", 
      "N", 
      "N", 
      "N", 
      "N", 
      0, 
      "N", 
      "N", 
      "N", 
      0, 
      "N", 
      "N", 
      0, 
      0, 
      0, 
      "N", 
      "N", 
      "N", 
      "N", 
      "1", 
      "N", 
      "N", 
      "", 
      0, 
      "N", 
      "", 
      0, 
      "2", 
      "0", 
      "N", 
      0, 
      0, 
      0, 
      "N", 
      0, 
      "0", 
      "0", 
      "", 
      "1", 
      "0", 
      "1", 
      "N", 
      "N", 
      "N", 
      0, 
      "N", 
      "N", 
      "0", 
      0, 
      "N", 
      "N", 
      0, 
      0, 
      "", 
      "N", 
      "N", 
      0, 
      "", 
      "N", 
      "0", 
      "9", 
      "N", 
      0, 
      0, 
      1, 
      1, 
      "N", 
      "N", 
      "N", 
      "N", 
      0, 
      "Y", 
      "N", 
      0, 
      "N", 
      "N", 
      0, 
      "N", 
      "0", 
      1, 
      0, 
      0, 
      0, 
      0, 
      401, 
      "2017-03-17 00:00:00", 
      "2017-03-17 00:00:00", 
      401, 
      "2017-04-06 00:00:00", 
      "2017-04-06 00:00:00", 
      0, 
      "", 
      0, 
      "", 
      10000000000000000, 
      1, 
      10000000000000000, 
      0, 
      1, 
      1, 
      "", 
      0, 
      0, 
      "", 
      "", 
      "", 
      0, 
      "", 
      "", 
      "", 
      0, 
      "", 
      "", 
      0, 
      "", 
      0, 
      0, 
      "", 
      0, 
      0, 
      "", 
      0, 
      0, 
      0, 
      0, 
      0, 
      "", 
      "", 
      "", 
      "", 
      0, 
      "", 
      "", 
      0, 
      "", 
      ""
    ], 
    "_meta": {
      "_cols": [
        "organId", 
        "productName", 
        "productAbbr", 
        "internalId", 
        "hospitalType", 
        "unitFlag", 
        "insType", 
        "ally", 
        "individualGroup", 
        "value", 
        "exception", 
        "startDate", 
        "endDate", 
        "lifeRate", 
        "suddenRate", 
        "illRate", 
        "em", 
        "checkAmount", 
        "pregnantInsured", 
        "underwriteClass", 
        "attachable", 
        "insureMonth", 
        "duty", 
        "benefitType", 
        "targetType", 
        "periodType", 
        "underwriteJob", 
        "actuaryRate", 
        "tablePrem", 
        "ssClaimFormula", 
        "minClaimAmount", 
        "mortagage", 
        "initialId", 
        "sectionCalType", 
        "periodCalType", 
        "ageBase", 
        "bonusCalType", 
        "premiumDefine", 
        "reguToSingle", 
        "saAccum", 
        "universalPrem", 
        "checked", 
        "sysLockTime", 
        "sysLockerId", 
        "sysLockStatus", 
        "pseudo", 
        "policyholder", 
        "premTable", 
        "commAmount", 
        "uwManual", 
        "baseMoney", 
        "gstIndicator", 
        "stampIndicator", 
        "planType", 
        "ageMethod", 
        "rnDateType", 
        "followDiscnt", 
        "deferPeriod", 
        "waiver", 
        "waiverBenefit", 
        "maxSwitchTimes", 
        "switchPeriodUnit", 
        "maxSwitInTimes", 
        "maxSwitOutTimes", 
        "minSurValue", 
        "minRemainValue", 
        "minDeferPeriod", 
        "maxDeferPeriod", 
        "productName2", 
        "featureDesc", 
        "payerWop", 
        "maxWaivPremAnn", 
        "gurntPeriodType", 
        "receiptIndi", 
        "fullDeclare", 
        "phLaRelation", 
        "hthFullDeclare", 
        "advanProgram", 
        "uwJet", 
        "backdateIndi", 
        "startBackdate", 
        "backdatePeriod", 
        "postdateIndi", 
        "maxCompCommi", 
        "doppIndi", 
        "policySection", 
        "conversionPriv", 
        "purcNewPol", 
        "laChange", 
        "standAloneRider", 
        "partialWithdraw", 
        "investDelay", 
        "cashBonusIndi", 
        "revBonusIndi", 
        "tmlBonusIndi", 
        "tmlBonusIntRate", 
        "bereavementIndi", 
        "standLifeIndi", 
        "nonLapPeriod", 
        "switchFee", 
        "freeSwitchTimes", 
        "incrPremPermit", 
        "surrChargeIndi", 
        "specialDiscnt", 
        "apilpIndi", 
        "backdateUnit", 
        "topupPermit", 
        "regTopupPermit", 
        "gurntPeriodUnit", 
        "gurntPeriod", 
        "hiPolFeeIndi", 
        "freeSwitchUnit", 
        "freeSwitchPeriod", 
        "parNonIlp", 
        "stampdutyOption", 
        "ladrIndi", 
        "bonusVestYearClm", 
        "bonusVestYearSurr", 
        "cbVestYear", 
        "isNetInvest", 
        "gsvVestYear", 
        "phdRateCate", 
        "riCalcBasis", 
        "riCalcFormula", 
        "riRenewalFreq", 
        "riFactorTableCode", 
        "riAgeBase", 
        "assetShare", 
        "gjaIndi", 
        "gscIndi", 
        "apilpK", 
        "uptoageIndi", 
        "spouseProdIndi", 
        "benefitFreqIndi", 
        "riskAggrFormula", 
        "premChangeNotice", 
        "aurpSpecificTerms", 
        "waiverInterestRate", 
        "dbBaseClm", 
        "bucketFillingOption", 
        "followCommision", 
        "formulaDriven", 
        "valueUnitAmount", 
        "valueCalType", 
        "commStartDdIndi", 
        "finProdIndicator", 
        "raObject", 
        "regPartWitdrPer", 
        "bucketFillOptionAd", 
        "pldGracePeriod", 
        "lapseMethod", 
        "freeWitdrTimes", 
        "spouseWaiver", 
        "persAnnuTaxTerm", 
        "fullPrepayment", 
        "selfConfirm", 
        "waitDaysAfLapse", 
        "editable", 
        "hasFlexiblePeriod", 
        "flexiblePeriod", 
        "firstOfMonth", 
        "indxIndi", 
        "indxYear", 
        "autoBackdateIndi", 
        "familyType", 
        "modelFactorRateAn", 
        "investDelayOption", 
        "lockInPeriod", 
        "lockInPeriodOption", 
        "investFreelookOption", 
        "insertedBy", 
        "insertTime", 
        "insertTimestamp", 
        "updatedBy", 
        "updateTime", 
        "updateTimestamp", 
        "insertPerson", 
        "insertDate", 
        "updaterId", 
        "autoReinstmtIndi", 
        "maxSurValue", 
        "partialWithdrawStartYear", 
        "regPartWitdrMaxAmount", 
        "regPartWitdrMinAmount", 
        "regPartWitdrStartYear", 
        "topupStartYear", 
        "addPermit", 
        "adminCharge", 
        "annuitySurrFac", 
        "aplPermit", 
        "assignmentIndi", 
        "autoReducePaidup", 
        "autoReinstmtPeriod", 
        "bonusEncash", 
        "decreasePermit", 
        "etaPermit", 
        "etaProductId", 
        "freeLookFollow", 
        "freeLookIndi", 
        "freeLookPeriod", 
        "graceFollow", 
        "gracePeriod", 
        "gracePeriodAdd", 
        "loanPermit", 
        "maxLoanRate", 
        "maxReinsPeriod", 
        "maxReinsPeriUnit", 
        "minAddAmount", 
        "minAddUnits", 
        "minLoanAmt", 
        "minSurAmount", 
        "minSurUnits", 
        "overdueIntIndi", 
        "permitPrs", 
        "preferLifeIndi", 
        "premVouchPermit", 
        "premVouchRate", 
        "reducePaidup", 
        "renew", 
        "rupProductId", 
        "specialRevivalPermit", 
        "surrPermit"
      ], 
      "_coltypes": [
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "dtm", 
        "dtm", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "dtm", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "dtm", 
        "num", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "num", 
        "num", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "num", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "dtm", 
        "dtm", 
        "num", 
        "dtm", 
        "dtm", 
        "num", 
        "dtm", 
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "str", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "str", 
        "num", 
        "num", 
        "str", 
        "num", 
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str"
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "num"
        ]
      ]
    }
  }, 
  "productSaLimit": {
    "10001001:*:*:*:0:0:0": [
      30000000, 
      750000000, 
      0, 
      99999, 
      0, 
      99999
    ], 
    "_meta": {
      "_cols": [
        "insdMinAmount", 
        "insdMaxAmount", 
        "premiumMinFactor", 
        "premiumMaxFactor", 
        "incomeMinFactor", 
        "incomeMaxFactor"
      ], 
      "_coltypes": [
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num"
      ], 
      "_key_ageMonth": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_gender": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_insuredStatus": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_job": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "num"
        ], 
        [
          "ageMonth", 
          "num"
        ], 
        [
          "gender", 
          "str"
        ], 
        [
          "job", 
          "str"
        ], 
        [
          "insuredStatus", 
          "str"
        ], 
        [
          "payMode", 
          "num"
        ], 
        [
          "specialAuth", 
          "num"
        ]
      ]
    }
  }, 
  "revBonusRate": {}, 
  "saLimit": {
    "10001001:0:0:0:0:0": [
      10130543, 
      "1", 
      30000000, 
      750000000, 
      401, 
      "2017-03-17 00:00:00", 
      401, 
      "2017-03-17 00:00:00", 
      "0", 
      30, 
      "2017-03-17 00:00:00", 
      "2017-03-17 00:00:00", 
      10130529
    ], 
    "10001001:0:0:216:0:0": [
      10130534, 
      "1", 
      30000000, 
      2000000000, 
      401, 
      "2017-03-17 00:00:00", 
      401, 
      "2017-03-17 00:00:00", 
      "0", 
      30, 
      "2017-03-17 00:00:00", 
      "2017-03-17 00:00:00", 
      10130529
    ], 
    "_meta": {
      "_cols": [
        "listId", 
        "limitUnit", 
        "insdMinAmount", 
        "insdMaxAmount", 
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "declarationType", 
        "moneyId", 
        "insertTimestamp", 
        "updateTimestamp", 
        "productVersionId"
      ], 
      "_coltypes": [
        "num", 
        "str", 
        "num", 
        "num", 
        "num", 
        "dtm", 
        "num", 
        "dtm", 
        "str", 
        "num", 
        "dtm", 
        "dtm", 
        "num"
      ], 
      "_key_ageMonth": [
        [
          "216", 
          "9999"
        ], 
        [
          "0", 
          "215"
        ]
      ], 
      "_key_insuredStatus": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_jobCate": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "10001001", 
          "*"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "num"
        ], 
        [
          "payMode", 
          "num"
        ], 
        [
          "insuredStatus", 
          "str"
        ], 
        [
          "ageMonth", 
          "num"
        ], 
        [
          "jobCate", 
          "num"
        ], 
        [
          "specialAuth", 
          "num"
        ]
      ]
    }
  }, 
  "tmlBonusRate": {}
}