module.exports={
  "ageLimit": {
    "4671:0:0:9999:0:0:9999:0:0:0:0:9999:0:0:0.0:0:N:0:0": [
      3081, 
      "1", 
      16, 
      55, 
      60, 
      60, 
      60, 
      60, 
      60, 
      999, 
      999, 
      "1", 
      0, 
      999, 
      999, 
      "1", 
      0, 
      999, 
      400, 
      "2008-11-28 00:00:00", 
      400, 
      "2010-07-28 00:00:00", 
      "1", 
      0, 
      "1", 
      "1", 
      9999, 
      999
    ], 
    "_meta": {
      "_cols": [
        "listId", 
        "minInsdNbAgeUnit", 
        "minInsdNbAge", 
        "maxInsdNbAge", 
        "maxInsdRnAge", 
        "maxInsdNbPuAge", 
        "maxInsdRnPuAge", 
        "maxInsdNbExAge", 
        "maxInsdRnExAge", 
        "maxPhNbAge", 
        "maxPhRnAge", 
        "minJiNbAgeUnit", 
        "minJiNbAge", 
        "maxJiNbAge", 
        "maxJiRnAge", 
        "minTopupAgeUnit", 
        "minTopupAge", 
        "maxTopupAge", 
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "maxInsdNbAgeUnit", 
        "minPhNbAge", 
        "maxJiNbAgeUnit", 
        "maxTopupAgeUnit", 
        "payYearMax", 
        "maxDefermentAge"
      ], 
      "_coltypes": [
        "int", 
        "str", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "str", 
        "int", 
        "int", 
        "int", 
        "str", 
        "int", 
        "int", 
        "int", 
        "dtm", 
        "int", 
        "dtm", 
        "str", 
        "int", 
        "str", 
        "str", 
        "int", 
        "int"
      ], 
      "_key_chargePeriod": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_chargeType": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_chargeYear": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_chargeYearMax": [
        [
          "9999", 
          "*"
        ]
      ], 
      "_key_coveragePeriod": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_coverageYear": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_coverageYearMax": [
        [
          "9999", 
          "*"
        ]
      ], 
      "_key_endPeriod": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_endYear": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_endYearMax": [
        [
          "9999", 
          "*"
        ]
      ], 
      "_key_gender": [
        [
          "N", 
          "*"
        ]
      ], 
      "_key_insuredStatus": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payEnsure": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payPeriod": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payYear": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_key_sa": [
        [
          "0.0", 
          "9999999999.0"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "chargePeriod", 
          "str"
        ], 
        [
          "chargeYear", 
          "int"
        ], 
        [
          "chargeYearMax", 
          "int"
        ], 
        [
          "coveragePeriod", 
          "str"
        ], 
        [
          "coverageYear", 
          "int"
        ], 
        [
          "coverageYearMax", 
          "int"
        ], 
        [
          "payPeriod", 
          "str"
        ], 
        [
          "payYear", 
          "int"
        ], 
        [
          "endPeriod", 
          "str"
        ], 
        [
          "endYear", 
          "int"
        ], 
        [
          "endYearMax", 
          "int"
        ], 
        [
          "payEnsure", 
          "int"
        ], 
        [
          "chargeType", 
          "str"
        ], 
        [
          "sa", 
          "num"
        ], 
        [
          "payMode", 
          "int"
        ], 
        [
          "gender", 
          "str"
        ], 
        [
          "insuredStatus", 
          "str"
        ], 
        [
          "specialAuth", 
          "int"
        ]
      ]
    }
  }, 
  "cashBonusRate": {}, 
  "cashValue": {}, 
  "liabilityConfig": {}, 
  "modelFactor": {
    "4671:1:1:*": [
      1.0, 
      1.0
    ], 
    "4671:2:1:*": [
      0.535, 
      1.0
    ], 
    "4671:3:1:*": [
      0.2725, 
      1.0
    ], 
    "4671:4:1:*": [
      0.0925, 
      1.0
    ], 
    "_meta": {
      "_cols": [
        "chargeRate", 
        "chargeRateDiv"
      ], 
      "_coltypes": [
        "num", 
        "num"
      ], 
      "_key_chargeType": [
        [
          "4", 
          "*"
        ], 
        [
          "1", 
          "*"
        ], 
        [
          "2", 
          "*"
        ], 
        [
          "3", 
          "*"
        ]
      ], 
      "_key_modelType": [
        [
          "1", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "chargeType", 
          "str"
        ], 
        [
          "modelType", 
          "int"
        ], 
        [
          "payMode", 
          "int"
        ]
      ]
    }
  }, 
  "payLiability": {}, 
  "premLimit": {
    "4671:0:0:0:0": [
      2337, 
      0.0, 
      100000000000000.0, 
      0.0, 
      100000000000000.0, 
      0.0, 
      0.0, 
      0.0, 
      0.0, 
      400, 
      "2008-11-28 00:00:00", 
      400, 
      "2008-11-28 00:00:00", 
      0.0, 
      0.0
    ], 
    "_meta": {
      "_cols": [
        "listId", 
        "minInitialPrem", 
        "maxInitialPrem", 
        "minSubseqPrem", 
        "maxSubseqPrem", 
        "minIncremntPrem", 
        "minReguTopupPrem", 
        "minReguTopupIncr", 
        "minAdTopupPrem", 
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "minDecremntPrem", 
        "minReguTopupDecr"
      ], 
      "_coltypes": [
        "int", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "int", 
        "dtm", 
        "int", 
        "dtm", 
        "num", 
        "num"
      ], 
      "_key_age": [
        [
          "0", 
          "999"
        ]
      ], 
      "_key_chargeType": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "chargeType", 
          "str"
        ], 
        [
          "age", 
          "int"
        ], 
        [
          "payMode", 
          "int"
        ], 
        [
          "specialAuth", 
          "int"
        ]
      ]
    }
  }, 
  "premiumRate": {
    "4671:*:*:1:*:*:1900-01-01:*": [
      2.0
    ], 
    "4671:*:*:2:*:*:1900-01-01:*": [
      3.3
    ], 
    "4671:*:*:3:*:*:1900-01-01:*": [
      4.5
    ], 
    "_meta": {
      "_cols": [
        "resultValue1"
      ], 
      "_coltypes": [
        "num"
      ], 
      "_key_age": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_benefitLevel": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_effectiveDate": [
        [
          "1900-01-01", 
          "9999-09-09"
        ]
      ], 
      "_key_gender": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_jobClass": [
        [
          "1", 
          "*"
        ], 
        [
          "3", 
          "*"
        ], 
        [
          "2", 
          "*"
        ]
      ], 
      "_key_period": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_premiumYear": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "premiumYear", 
          "int"
        ], 
        [
          "period", 
          "int"
        ], 
        [
          "jobClass", 
          "int"
        ], 
        [
          "age", 
          "int"
        ], 
        [
          "gender", 
          "str"
        ], 
        [
          "effectiveDate", 
          "dtm"
        ], 
        [
          "benefitLevel", 
          "int"
        ]
      ]
    }
  }, 
  "prodFundPremLimit": {}, 
  "productAllowables": {
    "attachableRiders": [
      [], 
      [
        "int", 
        "str", 
        "str", 
        "str"
      ], 
      [
        "attachId", 
        "attachType", 
        "attachCompulsory", 
        "gender"
      ]
    ], 
    "bonusOptions": [
      [], 
      [
        "int"
      ], 
      [
        "modeId"
      ]
    ], 
    "coverageTerms": [
      [
        [
          "3", 
          60
        ]
      ], 
      [
        "str", 
        "int"
      ], 
      [
        "coveragePeriod", 
        "coverageYear"
      ]
    ], 
    "currencies": [
      [
        [
          30
        ]
      ], 
      [
        "int"
      ], 
      [
        "moneyId"
      ]
    ], 
    "funds": [
      [], 
      [
        "str"
      ], 
      [
        "fundCode"
      ]
    ], 
    "organizations": [
      [
        [
          101
        ]
      ], 
      [
        "int"
      ], 
      [
        "organId"
      ]
    ], 
    "payMethods": [
      [
        [
          "1", 
          "0", 
          1
        ], 
        [
          "1", 
          "0", 
          2
        ], 
        [
          "1", 
          "0", 
          3
        ], 
        [
          "1", 
          "0", 
          15
        ], 
        [
          "1", 
          "0", 
          22
        ], 
        [
          "1", 
          "0", 
          23
        ], 
        [
          "1", 
          "0", 
          30
        ], 
        [
          "1", 
          "0", 
          33
        ], 
        [
          "1", 
          "0", 
          80
        ], 
        [
          "1", 
          "0", 
          92
        ], 
        [
          "1", 
          "0", 
          93
        ], 
        [
          "1", 
          "0", 
          94
        ], 
        [
          "1", 
          "0", 
          96
        ], 
        [
          "1", 
          "0", 
          97
        ], 
        [
          "2", 
          "0", 
          1
        ], 
        [
          "2", 
          "0", 
          2
        ], 
        [
          "2", 
          "0", 
          3
        ], 
        [
          "2", 
          "0", 
          15
        ], 
        [
          "2", 
          "0", 
          22
        ], 
        [
          "2", 
          "0", 
          23
        ], 
        [
          "2", 
          "0", 
          30
        ], 
        [
          "2", 
          "0", 
          33
        ], 
        [
          "2", 
          "0", 
          80
        ], 
        [
          "2", 
          "0", 
          92
        ], 
        [
          "2", 
          "0", 
          93
        ], 
        [
          "2", 
          "0", 
          94
        ], 
        [
          "2", 
          "0", 
          96
        ], 
        [
          "2", 
          "0", 
          97
        ], 
        [
          "3", 
          "0", 
          1
        ], 
        [
          "3", 
          "0", 
          2
        ], 
        [
          "3", 
          "0", 
          3
        ], 
        [
          "3", 
          "0", 
          15
        ], 
        [
          "3", 
          "0", 
          22
        ], 
        [
          "3", 
          "0", 
          23
        ], 
        [
          "3", 
          "0", 
          30
        ], 
        [
          "3", 
          "0", 
          33
        ], 
        [
          "3", 
          "0", 
          80
        ], 
        [
          "3", 
          "0", 
          92
        ], 
        [
          "3", 
          "0", 
          93
        ], 
        [
          "3", 
          "0", 
          94
        ], 
        [
          "3", 
          "0", 
          96
        ], 
        [
          "3", 
          "0", 
          97
        ], 
        [
          "4", 
          "0", 
          1
        ], 
        [
          "4", 
          "0", 
          2
        ], 
        [
          "4", 
          "0", 
          3
        ], 
        [
          "4", 
          "0", 
          15
        ], 
        [
          "4", 
          "0", 
          22
        ], 
        [
          "4", 
          "0", 
          23
        ], 
        [
          "4", 
          "0", 
          30
        ], 
        [
          "4", 
          "0", 
          33
        ], 
        [
          "4", 
          "0", 
          80
        ], 
        [
          "4", 
          "0", 
          92
        ], 
        [
          "4", 
          "0", 
          93
        ], 
        [
          "4", 
          "0", 
          94
        ], 
        [
          "4", 
          "0", 
          96
        ], 
        [
          "4", 
          "0", 
          97
        ]
      ], 
      [
        "str", 
        "str", 
        "int"
      ], 
      [
        "chargeType", 
        "premSequen", 
        "payMode"
      ]
    ], 
    "paymentFreq": [
      [
        [
          "4"
        ], 
        [
          "1"
        ], 
        [
          "2"
        ], 
        [
          "3"
        ]
      ], 
      [
        "str"
      ], 
      [
        "chargeType"
      ]
    ], 
    "premiumTerms": [
      [
        [
          "3", 
          60
        ]
      ], 
      [
        "str", 
        "int"
      ], 
      [
        "chargePeriod", 
        "chargeYear"
      ]
    ], 
    "qualifications": [
      [
        [
          0
        ]
      ], 
      [
        "int"
      ], 
      [
        "testTypeId"
      ]
    ], 
    "strategies": [
      [], 
      [
        "str", 
        "int"
      ], 
      [
        "strategyCode", 
        "tariffType"
      ]
    ], 
    "survivalOptions": [
      [], 
      [
        "str"
      ], 
      [
        "survivalOption"
      ]
    ]
  }, 
  "productChargeList": {}, 
  "productCurrency": {
    "4671:101:30:0": [
      400, 
      "2030-02-08 00:00:00", 
      400, 
      "2030-02-08 00:00:00", 
      "0"
    ], 
    "_meta": {
      "_cols": [
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "entityFund"
      ], 
      "_coltypes": [
        "int", 
        "dtm", 
        "int", 
        "dtm", 
        "str"
      ], 
      "_key_entityFundType": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_moneyId": [
        [
          "30", 
          "*"
        ]
      ], 
      "_key_organId": [
        [
          "101", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "organId", 
          "int"
        ], 
        [
          "moneyId", 
          "int"
        ], 
        [
          "entityFundType", 
          "str"
        ]
      ]
    }
  }, 
  "productFund": {}, 
  "productLife": {
    "4671": [
      1, 
      "Accidental Death and Disablement", 
      "TADD01", 
      "TADD01", 
      "", 
      "2", 
      "2", 
      "0", 
      "1", 
      "N", 
      "", 
      "2000-01-01 00:00:00", 
      "2999-01-01 00:00:00", 
      0.0, 
      0.0, 
      0.0, 
      9999, 
      9999999999.0, 
      "N", 
      "Y", 
      "", 
      "N", 
      "N", 
      "", 
      "31", 
      "0", 
      "3", 
      "3", 
      "0", 
      "Y", 
      "N", 
      "N", 
      0.0, 
      "Y", 
      "", 
      "N", 
      0.0, 
      0.0, 
      0, 
      0, 
      0.0, 
      "N", 
      "ADD", 
      "1", 
      "1", 
      "1", 
      "", 
      "1", 
      "N", 
      "Y", 
      "N", 
      "N", 
      "Y", 
      400, 
      "2005-11-17 00:00:00", 
      401, 
      "2015-05-05 00:00:00", 
      "", 
      0, 
      "0", 
      "N", 
      "N", 
      0, 
      0, 
      "", 
      "1", 
      "N", 
      "N", 
      "N", 
      "N", 
      "N", 
      "N", 
      "N", 
      30, 
      "0", 
      "1", 
      "1", 
      45, 
      "Y", 
      "2", 
      "4", 
      "N", 
      "N", 
      "N", 
      0, 
      "N", 
      0.0, 
      "N", 
      "N", 
      "0", 
      9999, 
      "1", 
      9999, 
      9999, 
      0, 
      0, 
      0.0, 
      0.0, 
      0, 
      99, 
      "0", 
      "ACCIDENT BENEFIT)", 
      "Accidental Death & Disablement Rider - Traditional", 
      "N", 
      9999999999.0, 
      "2", 
      "N", 
      "N", 
      "N", 
      "1", 
      "N", 
      "N", 
      "N", 
      "Y", 
      "2004-01-01 00:00:00", 
      999, 
      "N", 
      0.0, 
      "N", 
      "0", 
      "Y", 
      "N", 
      "N", 
      "0", 
      "N", 
      "N", 
      "Y", 
      "Y", 
      0.0, 
      "N", 
      "N", 
      0, 
      "N", 
      "N", 
      "N", 
      0, 
      0.0, 
      "N", 
      3, 
      "N", 
      30, 
      "N", 
      0, 
      0.0, 
      0, 
      1.0, 
      999, 
      "N", 
      "1", 
      "N", 
      "N", 
      "N", 
      "1", 
      "N", 
      "N", 
      "1", 
      0, 
      "N", 
      0, 
      "Y", 
      0, 
      0.0, 
      "N", 
      "0", 
      999, 
      "Y", 
      "N", 
      "", 
      0, 
      "2", 
      "N", 
      0.0, 
      "N", 
      "N", 
      "0", 
      "N", 
      0, 
      0, 
      0, 
      "N", 
      "N", 
      "0", 
      0, 
      "0", 
      "3", 
      0, 
      "2", 
      "0", 
      "2", 
      "N", 
      "N", 
      "N", 
      0.0, 
      "N", 
      "N", 
      "0", 
      0, 
      "N", 
      "N", 
      0.0, 
      0.0, 
      "0", 
      "N", 
      "N", 
      0, 
      "0", 
      "N", 
      "0", 
      "9", 
      0.0, 
      "N", 
      0, 
      0, 
      1, 
      0, 
      "N", 
      "N", 
      "N", 
      "N", 
      0, 
      "Y", 
      "N", 
      0, 
      "Y", 
      "N", 
      "0", 
      0, 
      "N", 
      0, 
      "Y", 
      "N", 
      0, 
      "N", 
      2, 
      "N"
    ], 
    "_meta": {
      "_cols": [
        "organId", 
        "productName", 
        "productAbbr", 
        "internalId", 
        "hospitalType", 
        "unitFlag", 
        "insType", 
        "ally", 
        "individualGroup", 
        "value", 
        "exception", 
        "startDate", 
        "endDate", 
        "lifeRate", 
        "suddenRate", 
        "illRate", 
        "em", 
        "checkAmount", 
        "renew", 
        "pregnantInsured", 
        "underwriteClass", 
        "attachable", 
        "insureMonth", 
        "duty", 
        "benefitType", 
        "targetType", 
        "periodType", 
        "underwriteJob", 
        "surrPermit", 
        "addPermit", 
        "aplPermit", 
        "loanPermit", 
        "actuaryRate", 
        "tablePrem", 
        "ssClaimFormula", 
        "reducePaidup", 
        "minSurAmount", 
        "minAddAmount", 
        "minAddUnits", 
        "minSurUnits", 
        "minClaimAmount", 
        "mortagage", 
        "initialId", 
        "sectionCalType", 
        "periodCalType", 
        "ageBase", 
        "bonusCalType", 
        "premiumDefine", 
        "reguToSingle", 
        "saAccum", 
        "universalPrem", 
        "guaranteeRenew", 
        "checked", 
        "insertPerson", 
        "insertDate", 
        "updaterId", 
        "updateTime", 
        "sysLockTime", 
        "sysLockerId", 
        "sysLockStatus", 
        "pseudo", 
        "permitPrs", 
        "prsUnitAmount", 
        "prsFormula", 
        "policyholder", 
        "premTable", 
        "relatedTypePrem2", 
        "relatedPrem2", 
        "feeYearPrem2", 
        "agePrem2", 
        "genderPrem2", 
        "commAmount", 
        "uwManual", 
        "baseMoney", 
        "gstIndicator", 
        "stampIndicator", 
        "planType", 
        "gracePeriod", 
        "graceFollow", 
        "ageMethod", 
        "rnDateType", 
        "followDiscnt", 
        "largeSaDiscnt", 
        "premVouchPermit", 
        "premVouchRate", 
        "deferPeriod", 
        "jointAdjustRate", 
        "waiver", 
        "waiverBenefit", 
        "waiverBasis", 
        "maxSwitchTimes", 
        "switchPeriodUnit", 
        "maxSwitInTimes", 
        "maxSwitOutTimes", 
        "rupProductId", 
        "etaProductId", 
        "minSurValue", 
        "minRemainValue", 
        "minDeferPeriod", 
        "maxDeferPeriod", 
        "switchMethod", 
        "productName2", 
        "featureDesc", 
        "payerWop", 
        "maxWaivPremAnn", 
        "gurntPeriodType", 
        "receiptIndi", 
        "proofAge", 
        "fullDeclare", 
        "phLaRelation", 
        "hthFullDeclare", 
        "advanProgram", 
        "uwJet", 
        "backdateIndi", 
        "startBackdate", 
        "backdatePeriod", 
        "postdateIndi", 
        "maxCompCommi", 
        "doppIndi", 
        "policySection", 
        "assignmentIndi", 
        "conversionPriv", 
        "purcNewPol", 
        "unexpireRateMeth", 
        "bonusEncash", 
        "laChange", 
        "freeLookIndi", 
        "freeLookFollow", 
        "adminCharge", 
        "standAloneRider", 
        "partialWithdraw", 
        "investDelay", 
        "cashBonusIndi", 
        "revBonusIndi", 
        "tmlBonusIndi", 
        "etaEndoProd", 
        "tmlBonusIntRate", 
        "bereavementIndi", 
        "maxReinsPeriod", 
        "etaPermit", 
        "freeLookPeriod", 
        "standLifeIndi", 
        "nonLapPeriod", 
        "switchFee", 
        "freeSwitchTimes", 
        "maxGibRate", 
        "maxGibAge", 
        "incrPremPermit", 
        "maxReinsPeriUnit", 
        "surrChargeIndi", 
        "specialDiscnt", 
        "apilpIndi", 
        "backdateUnit", 
        "topupPermit", 
        "regTopupPermit", 
        "gurntPeriodUnit", 
        "gurntPeriod", 
        "hiPolFeeIndi", 
        "gracePeriodAdd", 
        "overdueIntIndi", 
        "etaTermProd", 
        "annuitySurrFac", 
        "annuityNoticeIndi", 
        "annuityNoticeUnit", 
        "annuityNoticePeriod", 
        "decreasePermit", 
        "preferLifeIndi", 
        "freeSwitchUnit", 
        "freeSwitchPeriod", 
        "parNonIlp", 
        "gibPermit", 
        "maxLoanRate", 
        "matuLoanPermit", 
        "specialRevivalPermit", 
        "stampdutyOption", 
        "ladrIndi", 
        "bonusVestYearClm", 
        "bonusVestYearSurr", 
        "cbVestYear", 
        "isNetInvest", 
        "autoReducePaidup", 
        "afterEtaOption", 
        "gsvVestYear", 
        "phdRateCate", 
        "riCalcBasis", 
        "riCalcFormula", 
        "riRenewalFreq", 
        "riFactorTableCode", 
        "riAgeBase", 
        "assetShare", 
        "gjaIndi", 
        "gscIndi", 
        "apilpK", 
        "uptoageIndi", 
        "spouseProdIndi", 
        "benefitFreqIndi", 
        "riskAggrFormula", 
        "premChangeNotice", 
        "aurpSpecificTerms", 
        "waiverInterestRate", 
        "dbBaseClm", 
        "bucketFillingOption", 
        "followCommision", 
        "formulaDriven", 
        "valueUnitAmount", 
        "valueCalType", 
        "commStartDdIndi", 
        "finProdIndicator", 
        "raObject", 
        "minLoanAmt", 
        "regPartWitdrPer", 
        "bucketFillOptionAd", 
        "pldGracePeriod", 
        "lapseMethod", 
        "freeWitdrTimes", 
        "spouseWaiver", 
        "persAnnuTaxTerm", 
        "fullPrepayment", 
        "selfConfirm", 
        "waitDaysAfLapse", 
        "editable", 
        "hasFlexiblePeriod", 
        "flexiblePeriod", 
        "firstOfMonth", 
        "forwardAllowed", 
        "periodTypeForForward", 
        "maxPeriodForForward", 
        "indxIndi", 
        "indxYear", 
        "autoBackdateIndi", 
        "isGio", 
        "maxExerciseTime", 
        "isDebt", 
        "productIndicator", 
        "simplifyUw"
      ], 
      "_coltypes": [
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "dtm", 
        "dtm", 
        "num", 
        "num", 
        "num", 
        "int", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "num", 
        "num", 
        "int", 
        "int", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "int", 
        "dtm", 
        "int", 
        "dtm", 
        "dtm", 
        "int", 
        "str", 
        "str", 
        "str", 
        "int", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "int", 
        "int", 
        "int", 
        "int", 
        "num", 
        "num", 
        "int", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "dtm", 
        "int", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "int", 
        "num", 
        "str", 
        "int", 
        "str", 
        "int", 
        "str", 
        "int", 
        "num", 
        "int", 
        "num", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "int", 
        "str", 
        "int", 
        "num", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "str", 
        "int", 
        "int", 
        "int", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "num", 
        "num", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "num", 
        "str", 
        "int", 
        "int", 
        "int", 
        "int", 
        "str", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "int", 
        "str", 
        "str", 
        "str", 
        "int", 
        "str", 
        "int", 
        "str", 
        "str", 
        "int", 
        "str", 
        "int", 
        "str"
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ]
      ]
    }
  }, 
  "productSaLimit": {
    "4671:*:*:*:0:0:0": [
      10000000.0, 
      2000000000.0, 
      0, 
      99999, 
      0, 
      99999
    ], 
    "_meta": {
      "_cols": [
        "insdMinAmount", 
        "insdMaxAmount", 
        "premiumMinFactor", 
        "premiumMaxFactor", 
        "incomeMinFactor", 
        "incomeMaxFactor"
      ], 
      "_coltypes": [
        "num", 
        "num", 
        "num", 
        "num", 
        "num", 
        "num"
      ], 
      "_key_ageMonth": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_gender": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_insuredStatus": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_job": [
        [
          "*", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "ageMonth", 
          "num"
        ], 
        [
          "gender", 
          "str"
        ], 
        [
          "job", 
          "str"
        ], 
        [
          "insuredStatus", 
          "str"
        ], 
        [
          "payMode", 
          "int"
        ], 
        [
          "specialAuth", 
          "int"
        ]
      ]
    }
  }, 
  "productUnitRate": {
    "4671": [
      1000, 
      1000, 
      0, 
      0, 
      0, 
      0, 
      0, 
      0
    ], 
    "_meta": {
      "_cols": [
        "saUnitAmount", 
        "emUnitAmount", 
        "cashValueUnitAmount", 
        "mortUnitAmount", 
        "revBonusUnitAmount", 
        "cashBonusUnitAmount", 
        "tmlBonusUnitAmount", 
        "premiumUnitAmount"
      ], 
      "_coltypes": [
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int", 
        "int"
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ]
      ]
    }
  }, 
  "revBonusRate": {}, 
  "saLimit": {
    "4671:0:0:0:0:0": [
      3021, 
      "1", 
      10000000.0, 
      2000000000.0, 
      400, 
      "2010-01-09 00:00:00", 
      400, 
      "2010-08-09 00:00:00", 
      "0", 
      0
    ], 
    "_meta": {
      "_cols": [
        "listId", 
        "limitUnit", 
        "insdMinAmount", 
        "insdMaxAmount", 
        "recorderId", 
        "insertTime", 
        "updaterId", 
        "updateTime", 
        "declarationType", 
        "maxSaPerLife"
      ], 
      "_coltypes": [
        "int", 
        "str", 
        "num", 
        "num", 
        "int", 
        "dtm", 
        "int", 
        "dtm", 
        "str", 
        "int"
      ], 
      "_key_ageMonth": [
        [
          "0", 
          "9999"
        ]
      ], 
      "_key_insuredStatus": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_jobCate": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_payMode": [
        [
          "0", 
          "*"
        ]
      ], 
      "_key_productId": [
        [
          "4671", 
          "*"
        ]
      ], 
      "_key_specialAuth": [
        [
          "0", 
          "*"
        ]
      ], 
      "_keys": [
        [
          "productId", 
          "int"
        ], 
        [
          "payMode", 
          "int"
        ], 
        [
          "insuredStatus", 
          "str"
        ], 
        [
          "ageMonth", 
          "int"
        ], 
        [
          "jobCate", 
          "int"
        ], 
        [
          "specialAuth", 
          "int"
        ]
      ]
    }
  }, 
  "tmlBonusRate": {}
}