module.exports.salutions = {
  codeTableId :   "Salutation",
  codeTableDescription: "List of salutations for a person",
  codeTableData: [
    {code: "1", textValue:"Mrs."},
    {code: "2", textValue:"Mr."},
    {code: "3", textValue:"Dr."},
    {code: "4", textValue:"Mdm."},
    {code: "5", textValue:"Miss"},
    {code: "6", textValue:"Others"}
  ]
}

module.exports.idTypes = {
  codeTableId :   "IdType",
  codeTableDescription: "List of identification types for a person",
  codeTableData: [
    { code: "3",textValue: "Passport"},
    { code: "4",textValue: "Birth Certificate"},
    { code: "12",textValue: "Singaporean Born After Year 2000"},
    { code: "13",textValue: "Fin Number Issued Before Year 2000"},
    { code: "14",textValue: "Fin Number Issued After Year 2000"},
    { code: "15",textValue: "Brunei passport"},
    { code: "16",textValue: "Malaysia IC Number"},
    { code: "18",textValue: "Brunei IC"},
    { code: "19",textValue: "MALAYSIAN POLICE NO"},
    { code: "21",textValue: "HONG KONG IC"},
    { code: "22",textValue: "SABAH IC"},
    { code: "23",textValue: "SARAWAK IC"},
    { code: "24",textValue: "OLD MALAYSIAN IC"},
    { code: "26",textValue: "SINGAPOREAN IC"},
    { code: "28",textValue: "NEW MALAYSIAN IC"},
    { code: "30",textValue: "Dummy"},
    { code: "31",textValue: "Income Tax No"},
    { code: "32",textValue: "Driving License"},
    { code: "99",textValue: "Others"}  ]
}

module.exports.occupations = {
  codeTableId :   "Occupation",
  codeTableDescription: "List of occupations",
  codeTableData: [
    { code: "2", textValue: "Accountant "},
    { code: "3", textValue: "Accounts Assistant"},
    { code: "4", textValue: "Actor/Actress (no stunt)"},
    { code: "5", textValue: "Actuary"},
    { code: "6", textValue: "Admin Assistant"},
    { code: "7", textValue: "Administrator (Office-based)"},
    { code: "8", textValue: "Advertiser / Advertising Agent"},
    { code: "9", textValue: "Agent (estate/travel/insurance)"},
    { code: "10", textValue: "Aircraft Engineer"},
    { code: "11", textValue: "Airport Security (unarmed)"},
    { code: "12", textValue: "Architect"},
    { code: "13", textValue: "Artist"},
    { code: "14", textValue: "Athlete (track & field only)"},
    { code: "15", textValue: "Auctioneer"},
    { code: "16", textValue: "Auditor"},
    { code: "17", textValue: "Author"},
    { code: "18", textValue: "Baggage Porter"},
    { code: "19", textValue: "Baker"},
    { code: "20", textValue: "Bank Teller"},
    { code: "21", textValue: "Banker/Bank Officer"},
    { code: "22", textValue: "Barber"},
    { code: "23", textValue: "Bartender"},
    { code: "24", textValue: "Beautician"},
    { code: "25", textValue: "Blacksmith"},
    { code: "26", textValue: "Boat Man / Ferryman"},
    { code: "27", textValue: "Book Keeper"},
    { code: "28", textValue: "Broker (Insurance/Money/Stock)"},
    { code: "29", textValue: "Bus Inspector"},
    { code: "30", textValue: "Butcher"},
    { code: "31", textValue: "Cable splicer/ Lineman "},
    { code: "32", textValue: "Cabin Crew (Airlines)"},
    { code: "33", textValue: "Canteen Assistant / Operator"},
    { code: "34", textValue: "Car Park Attendant"},
    { code: "35", textValue: "Carpenter"},
    { code: "36", textValue: "Cashier"},
    { code: "37", textValue: "Chambermaid"},
    { code: "38", textValue: "Chauffeur"},
    { code: "39", textValue: "Chef / Cook"},
    { code: "40", textValue: "Chemist"},
    { code: "41", textValue: "Chief Executive Officer"},
    { code: "42", textValue: "Civil Engineer"},
    { code: "43", textValue: "Cleaner"},
    { code: "44", textValue: "Clerk / Clerical Officer"},
    { code: "45", textValue: "Clinic Assistant (non nursing staff)"},
    { code: "46", textValue: "Coach (Sports)"},
    { code: "47", textValue: "Computer Analyst / Programmer"},
    { code: "48", textValue: "Construction Foreman"},
    { code: "49", textValue: "Construction Site Worker"},
    { code: "50", textValue: "Consultant "},
    { code: "51", textValue: "Craftsman"},
    { code: "52", textValue: "Crane Driver/Tower Crane Operator"},
    { code: "53", textValue: "Cruise Crew (all crew members working onboard of cruise ship – in customer services only"},
    { code: "54", textValue: "Curator (museum)"},
    { code: "55", textValue: "Customer Service Officer"},
    { code: "56", textValue: "Dancer (Professional)"},
    { code: "57", textValue: "Dental Assistant / Nurse"},
    { code: "58", textValue: "Dentist"},
    { code: "59", textValue: "Designer (Interior)"},
    { code: "60", textValue: "Despatch / Delivery Man"},
    { code: "62", textValue: "Diplomat"},
    { code: "63", textValue: "Disc Jockey "},
    { code: "64", textValue: "Diving Instructor"},
    { code: "65", textValue: "Dock Worker"},
    { code: "66", textValue: "Doctor"},
    { code: "67", textValue: "Dog Trainer"},
    { code: "68", textValue: "Draughtsman"},
    { code: "69", textValue: "Driver (Bus / Taxi / van / coach / private car / ambulance)"},
    { code: "70", textValue: "Driver (Heavy Vehicle – Truck / Lorry / Container "},
    { code: "71", textValue: "Driving Instructor"},
    { code: "72", textValue: "Economist"},
    { code: "73", textValue: "Editor"},
    { code: "74", textValue: "Electrician (without Height involvement)"},
    { code: "75", textValue: "Engineer"},
    { code: "76", textValue: "Engineer (Admin / Office Based)"},
    { code: "77", textValue: "Entertainer"},
    { code: "78", textValue: "Executive (Office Based)"},
    { code: "79", textValue: "Factor Worker"},
    { code: "80", textValue: "Fashion Designer"},
    { code: "81", textValue: "Fashion Model"},
    { code: "82", textValue: "Financial Controller"},
    { code: "83", textValue: "Financial Planner / Adviser"},
    { code: "84", textValue: "Fireman"},
    { code: "85", textValue: "Fisherman (River / Lake / Coastal) "},
    { code: "86", textValue: "Fishmonger"},
    { code: "87", textValue: "Fitness Instructor"},
    { code: "88", textValue: "Florist"},
    { code: "89", textValue: "Forklift Driver"},
    { code: "90", textValue: "Garage Worker"},
    { code: "91", textValue: "Gardener"},
    { code: "92", textValue: "General Manager"},
    { code: "93", textValue: "General Worker"},
    { code: "94", textValue: "Goldsmith"},
    { code: "95", textValue: "Hairstylist "},
    { code: "96", textValue: "Hawker"},
    { code: "97", textValue: "Hotel (Public Relations Officer)"},
    { code: "98", textValue: "Housewife"},
    { code: "99", textValue: "Jeweller"},
    { code: "100", textValue: "Journalist (local & no war zone)"},
    { code: "101", textValue: "Judge "},
    { code: "102", textValue: "Juvenile"},
    { code: "103", textValue: "Labourer"},
    { code: "104", textValue: "Landscape Artist"},
    { code: "105", textValue: "Lawyer"},
    { code: "106", textValue: "Lecturer "},
    { code: "107", textValue: "Legal Adviser/Officer/Consultant"},
    { code: "108", textValue: "Librarian "},
    { code: "109", textValue: "Life Guard"},
    { code: "110", textValue: "Locksmith"},
    { code: "111", textValue: "Loss Adjustor"},
    { code: "112", textValue: "Machine Operator"},
    { code: "113", textValue: "Machinist"},
    { code: "114", textValue: "Manager (Office Based)"},
    { code: "115", textValue: "Managing Director"},
    { code: "116", textValue: "Marketing Staff (Office Based)"},
    { code: "117", textValue: "Masseur / Masseuse (International Hotel /Health Spa)"},
    { code: "118", textValue: "Mechanic (without Height Involvement)"},
    { code: "119", textValue: "Military – Administrative/Clerical Functions  (Not Combat"},
    { code: "120", textValue: "Military – Air Forc"},
    { code: "121", textValue: "Minister of Religion"},
    { code: "122", textValue: "Motor Cycle Delivery Rider"},
    { code: "123", textValue: "Motor Vehicle Dealer"},
    { code: "124", textValue: "Musician (Entertainer)"},
    { code: "125", textValue: "National Serviceman"},
    { code: "126", textValue: "News Broadcaster "},
    { code: "127", textValue: "Nurse"},
    { code: "128", textValue: "Odd Job Labourer"},
    { code: "129", textValue: "Oil Refinery Admin Personnel"},
    { code: "130", textValue: "Oil Refinery Worker (Inland)"},
    { code: "131", textValue: "Optician "},
    { code: "132", textValue: "Optometrist"},
    { code: "133", textValue: "Packer"},
    { code: "134", textValue: "Painter (Indoor)"},
    { code: "135", textValue: "Pastor"},
    { code: "136", textValue: "Pharmacist"},
    { code: "137", textValue: "Photographer (Studio/Indoor)"},
    { code: "138", textValue: "Photographer (Outdoor)"},
    { code: "139", textValue: "Pilot (Commercial – Passenger)"},
    { code: "140", textValue: "Plumber"},
    { code: "141", textValue: "Policeman (Officer, Gurkha Officer, excl  Traffic Police and Mobile Squad)"},
    { code: "142", textValue: "Police – Mobile Squa"},
    { code: "143", textValue: "Politician"},
    { code: "144", textValue: "Postman"},
    { code: "145", textValue: "President (Company)"},
    { code: "146", textValue: "Principal (School)"},
    { code: "147", textValue: "Prison Officer / Warden"},
    { code: "148", textValue: "Promoter (Sales)"},
    { code: "149", textValue: "Receptionist"},
    { code: "150", textValue: "Remisier"},
    { code: "151", textValue: "Renovation Contractor"},
    { code: "152", textValue: "Reporter (local, no flying, no war zone)"},
    { code: "153", textValue: "Research & Development Engineer"},
    { code: "154", textValue: "Retiree"},
    { code: "155", textValue: "Sales Personnel (Outdoor)"},
    { code: "156", textValue: "Seamstress "},
    { code: "157", textValue: "Secretary"},
    { code: "158", textValue: "Security Guard (Armed)"},
    { code: "159", textValue: "Security Guard (Unarmed)"},
    { code: "160", textValue: "Self-employed (non-manual intensive)"},
    { code: "161", textValue: "Shipping Admin Personnel"},
    { code: "162", textValue: "Shop Assistant / Manager (Administrative)"},
    { code: "163", textValue: "Singer (in reputable hotels, lounge)"},
    { code: "164", textValue: "Social Worker "},
    { code: "165", textValue: "Sole Proprietor"},
    { code: "166", textValue: "Statistician "},
    { code: "167", textValue: "Store Keeper"},
    { code: "168", textValue: "Student"},
    { code: "169", textValue: "Supervisor"},
    { code: "170", textValue: "Surgeon"},
    { code: "171", textValue: "Surveyor"},
    { code: "172", textValue: "Tailor"},
    { code: "173", textValue: "Teacher (Academic)"},
    { code: "174", textValue: "Teacher (PE full time)"},
    { code: "175", textValue: "Technical Officer (Admin)"},
    { code: "176", textValue: "Technician (Qualified)"},
    { code: "177", textValue: "Telephone Operator "},
    { code: "178", textValue: "Tele-marketeer "},
    { code: "179", textValue: "Tour Guide"},
    { code: "180", textValue: "Traffic Police"},
    { code: "181", textValue: "Tutor (Private)"},
    { code: "182", textValue: "Typist"},
    { code: "183", textValue: "Underwriter"},
    { code: "184", textValue: "Veterinary Surgeon"},
    { code: "185", textValue: "Waiter / Waitress"},
    { code: "186", textValue: "Welder (Not underwater/oil/gas / no height involvement)"},
    { code: "187", textValue: "Window Cleaner (above 20 ft)"},
    { code: "188", textValue: "Zoo Keeper"},
    { code: "189", textValue: "Other - Class 1"},
    { code: "190", textValue: "Other - Class 2"},
    { code: "191", textValue: "Other - Class 3"},
    { code: "192", textValue: "Other - Class 4"},
    { code: "193", textValue: "Other - Class TBC"},
    { code: "999", textValue: "Others"},
  ]
}


module.exports.employmentNatures = {
  codeTableId :   "EmploymentNature",
  codeTableDescription: "List of employment nature",
  codeTableData: [

    {code: "Accounting /Audit / Compliance/Risk" , textValue: "Accounting /Audit / Compliance/Risk" },
    {code: "Actuarial/Statistic" , textValue: "Actuarial/Statistic" },
    {code: "Advertising/Marketing/Public Relations / Corporate Communications" , textValue: "Advertising/Marketing/Public Relations / Corporate Communications" },
    {code: "Aerospace/Aviation" , textValue: "Aerospace/Aviation" },
    {code: "Agricultural/Chemicals/Forestry" , textValue: "Agricultural/Chemicals/Forestry" },
    {code: "Automotive/Manufacturing/Production" , textValue: "Automotive/Manufacturing/Production" },
    {code: "Bars/Pubs/ Entertainment Outlets/Coffee houses/" , textValue: "Bars/Pubs/ Entertainment Outlets/Coffee houses/" },
    {code: "Casino/TOTO/Gaming Joints / Betting" , textValue: "Casino/TOTO/Gaming Joints / Betting" },
    {code: "Company Secretarial services/ Taxation " , textValue: "Company Secretarial services/ Taxation" },
    {code: "Computers/ Information Technology / Electronics" , textValue: "Computers/ Information Technology / Electronics" },
    {code: "Construction /Engineering" , textValue: "Construction /Engineering" },
    {code: "Creative/Graphics / Designers" , textValue: "Creative/Graphics / Designers" },
    {code: "Customer Service / Human Resource" , textValue: "Customer Service / Human Resource" },
    {code: "Education/Training" , textValue: "Education/Training" },
    {code: "Energy/Mining" , textValue: "Energy/Mining" },
    {code: "Finance/Banking/Insurance" , textValue: "Finance/Banking/Insurance" },
    {code: "Foreign Offshore Banks/  Foreign Embassies" , textValue: "Foreign Offshore Banks/  Foreign Embassies" },
    {code: "Freight/Shipping/Geology" , textValue: "Freight/Shipping/Geology" },
    {code: "Guest Relations Officer / Escort Services" , textValue: "Guest Relations Officer / Escort Services" },
    {code: "Gold dealer, pawn shop, Gold Investment/ Antiques, Fur / Gemstones" , textValue: "Gold dealer, pawn shop, Gold Investment/ Antiques, Fur / Gemstones" },
    {code: "Government/Military/Armed Securities/Public Service" , textValue: "Government/Military/Armed Securities/Public Service" },
    {code: "High Luxury Item Dealers - Cars/ Boats/ Airplanes " , textValue: "High Luxury Item Dealers - Cars/ Boats/ Airplanes" },
    {code: "Hotel/ Catering/ Recreational Clubs" , textValue: "Hotel/ Catering/ Recreational Clubs" },
    {code: "Import and Export Trading" , textValue: "Import and Export Trading" },
    {code: "Investment Holding" , textValue: "Investment Holding" },
    {code: "Journalist/ Editor" , textValue: "Journalist/ Editor" },
    {code: "Legal Firm/Trustees/Will Writing/ Public /Chartered Accounting" , textValue: "Legal Firm/Trustees/Will Writing/ Public /Chartered Accounting" },
    {code: "Media/Publishing/Entertainment/Events" , textValue: "Media/Publishing/Entertainment/Events" },
    {code: "Medical / Health Services /Pharmaceuticals" , textValue: "Medical / Health Services /Pharmaceuticals" },
    {code: "Money Lender /Money Changer/Chettiah" , textValue: " Money Lender /Money Changer/Chettiah" },
    {code: "Offshore Corporations/ Cross Border Sales" , textValue: "Offshore Corporations/ Cross Border Sales" },
    {code: "Online Business/Non-face to Face" , textValue: "Online Business/Non-face to Face" },
    {code: "Non-Listed Banking/ ATM Vendors" , textValue: "Non-Listed Banking/ ATM Vendors" },
    {code: "Real Estate /Property" , textValue: "Real Estate /Property" },
    {code: "Recreation/Hospitality/Sports" , textValue: "Recreation/Hospitality/Sports" },
    {code: "Retails/ Restaurants/ Wholesales/ Convenience Stores / Car Wash/ Car Repair" , textValue: "Retails/ Restaurants/ Wholesales/ Convenience Stores / Car Wash/ Car Repair" },
    {code: "Religious Affairs/Religious Societies/ Religious Institution" , textValue: "Religious Affairs/Religious Societies/ Religious Institution" },
    {code: "Salons/massage Parleurs/Beauty Centers" , textValue: "Salons/massage Parleurs/Beauty Centers" },
    {code: "Stockbroking" , textValue: "Stockbroking" },
    {code: "Telecommunications/Networking" , textValue: "Telecommunications/Networking" },
    {code: "Travel Agencies/ Transportation" , textValue: "Travel Agencies/ Transportation" },
    {code: "Non-Income Earners /Housewives/Unemployed/Students" , textValue: "Non-Income Earners /Housewives/Unemployed/Students>" },
  ]
}

module.exports.insuranceObjectives = {
  codeTableId :   "InsuranceObjective",
  codeTableDescription: "List of reasons for buying the insurance",
  codeTableData: [
    {code: "PRO" , textValue: "Protection"},
    {code: "PRORET" , textValue: "Protection, Retirement"},
    {code: "LOANPRO" , textValue: "Loan Protection"},
    {code: "PROSAVINV" , textValue: "Protection, Savings, Investment"},
    {code: "EDU" , textValue: "Education"},
    {code: "PART" , textValue: "Partnership"},
    {code: "EB" , textValue: "Employee Benefit"},
    {code: "KEYMN" , textValue: "Keyman"},
    {code: "OTH" , textValue: "Others"},
  ]
}

module.exports.nationalities = {
  codeTableId :   "Nationality",
  codeTableDescription: "List of nationalities",
  codeTableData: [
    {code: "1", textValue: "Afghan"},
    {code: "2", textValue: "Albanian"},
    {code: "3", textValue: "Algerian"},
    {code: "4", textValue: "American"},
    {code: "5", textValue: "Andorran"},
    {code: "6", textValue: "Angolan"},
    {code: "7", textValue: "Antiguans"},
    {code: "8", textValue: "Argentinean"},
    {code: "9", textValue: "Armenian"},
    {code: "10", textValue: "Australian"},
    {code: "11", textValue: "Austrian"},
    {code: "12", textValue: "Azerbaijani"},
    {code: "13", textValue: "Bahamian"},
    {code: "14", textValue: "Bahraini"},
    {code: "15", textValue: "Bangladeshi"},
    {code: "16", textValue: "Barbadian"},
    {code: "17", textValue: "Barbudans"},
    {code: "18", textValue: "Batswana"},
    {code: "19", textValue: "Belarusian"},
    {code: "20", textValue: "Belgian"},
    {code: "21", textValue: "Belizean"},
    {code: "22", textValue: "Beninese"},
    {code: "23", textValue: "Bhutanese"},
    {code: "24", textValue: "Bolivian"},
    {code: "25", textValue: "Bosnian"},
    {code: "26", textValue: "Brazilian"},
    {code: "27", textValue: "British"},
    {code: "28", textValue: "Bruneian"},
    {code: "29", textValue: "Bulgarian"},
    {code: "30", textValue: "Burkinabe"},
    {code: "31", textValue: "Burmese"},
    {code: "32", textValue: "Burundian"},
    {code: "33", textValue: "Cambodian"},
    {code: "34", textValue: "Cameroonian"},
    {code: "35", textValue: "Canadian"},
    {code: "36", textValue: "Cape Verdean"},
    {code: "37", textValue: "Central African"},
    {code: "38", textValue: "Chadian"},
    {code: "39", textValue: "Chilean"},
    {code: "40", textValue: "Chinese"},
    {code: "41", textValue: "Colombian"},
    {code: "42", textValue: "Comoran"},
    {code: "44", textValue: "Congolese"},
    {code: "45", textValue: "Costa Rican"},
    {code: "46", textValue: "Croatian"},
    {code: "47", textValue: "Cuban"},
    {code: "48", textValue: "Cypriot"},
    {code: "49", textValue: "Czech"},
    {code: "50", textValue: "Danish"},
    {code: "51", textValue: "Djibouti"},
    {code: "53", textValue: "Dominican"},
    {code: "54", textValue: "Dutch"},
    {code: "55", textValue: "Dutchman"},
    {code: "56", textValue: "Dutchwoman"},
    {code: "57", textValue: "East Timorese"},
    {code: "58", textValue: "Ecuadorean"},
    {code: "59", textValue: "Egyptian"},
    {code: "60", textValue: "Emirian"},
    {code: "61", textValue: "Equatorial Guinean"},
    {code: "62", textValue: "Eritrean"},
    {code: "63", textValue: "Estonian"},
    {code: "64", textValue: "Ethiopian"},
    {code: "65", textValue: "Fijian"},
    {code: "66", textValue: "Filipino"},
    {code: "67", textValue: "Finnish"},
    {code: "68", textValue: "French"},
    {code: "69", textValue: "Gabonese"},
    {code: "70", textValue: "Gambian"},
    {code: "71", textValue: "Georgian"},
    {code: "72", textValue: "German"},
    {code: "73", textValue: "Ghanaian"},
    {code: "74", textValue: "Greek"},
    {code: "75", textValue: "Grenadian"},
    {code: "76", textValue: "Guatemalan"},
    {code: "77", textValue: "Guinea-Bissauan"},
    {code: "78", textValue: "Guinean"},
    {code: "79", textValue: "Guyanese"},
    {code: "80", textValue: "Haitian"},
    {code: "81", textValue: "Herzegovinian"},
    {code: "82", textValue: "Honduran"},
    {code: "83", textValue: "Hungarian"},
    {code: "84", textValue: "I-Kiribati"},
    {code: "85", textValue: "Icelander"},
    {code: "86", textValue: "Indian"},
    {code: "87", textValue: "Indonesian"},
    {code: "88", textValue: "Iranian"},
    {code: "89", textValue: "Iraqi"},
    {code: "91", textValue: "Irish"},
    {code: "92", textValue: "Israeli"},
    {code: "93", textValue: "Italian"},
    {code: "94", textValue: "Ivorian"},
    {code: "95", textValue: "Jamaican"},
    {code: "96", textValue: "Japanese"},
    {code: "97", textValue: "Jordanian"},
    {code: "98", textValue: "Kazakhstani"},
    {code: "99", textValue: "Kenyan"},
    {code: "100", textValue: "Kittian and Nevisian"},
    {code: "101", textValue: "Kuwaiti"},
    {code: "102", textValue: "Kyrgyz"},
    {code: "103", textValue: "Laotian"},
    {code: "104", textValue: "Latvian"},
    {code: "105", textValue: "Lebanese"},
    {code: "106", textValue: "Liberian"},
    {code: "107", textValue: "Libyan"},
    {code: "108", textValue: "Liechtensteiner"},
    {code: "109", textValue: "Lithuanian"},
    {code: "110", textValue: "Luxembourger"},
    {code: "111", textValue: "Macedonian"},
    {code: "112", textValue: "Malagasy"},
    {code: "113", textValue: "Malawian"},
    {code: "114", textValue: "Malaysian"},
    {code: "115", textValue: "Maldivan"},
    {code: "116", textValue: "Malian"},
    {code: "117", textValue: "Maltese"},
    {code: "118", textValue: "Marshallese"},
    {code: "119", textValue: "Mauritanian"},
    {code: "120", textValue: "Mauritian"},
    {code: "121", textValue: "Mexican"},
    {code: "122", textValue: "Micronesian"},
    {code: "123", textValue: "Moldovan"},
    {code: "124", textValue: "Monacan"},
    {code: "125", textValue: "Mongolian"},
    {code: "126", textValue: "Moroccan"},
    {code: "127", textValue: "Mosotho"},
    {code: "128", textValue: "Motswana"},
    {code: "129", textValue: "Mozambican"},
    {code: "130", textValue: "Namibian"},
    {code: "131", textValue: "Nauruan"},
    {code: "132", textValue: "Nepalese"},
    {code: "133", textValue: "Netherlander"},
    {code: "134", textValue: "New Zealander"},
    {code: "135", textValue: "Ni-Vanuatu"},
    {code: "136", textValue: "Nicaraguan"},
    {code: "137", textValue: "Nigerian"},
    {code: "138", textValue: "Nigerien"},
    {code: "139", textValue: "North Korean"},
    {code: "140", textValue: "Northern Irish"},
    {code: "141", textValue: "Norwegian"},
    {code: "142", textValue: "Omani"},
    {code: "143", textValue: "Pakistani"},
    {code: "144", textValue: "Palauan"},
    {code: "145", textValue: "Panamanian"},
    {code: "146", textValue: "Papua New Guinean"},
    {code: "147", textValue: "Paraguayan"},
    {code: "148", textValue: "Peruvian"},
    {code: "149", textValue: "Polish"},
    {code: "150", textValue: "Portuguese"},
    {code: "151", textValue: "Qatari"},
    {code: "152", textValue: "Romanian"},
    {code: "153", textValue: "Russian"},
    {code: "154", textValue: "Rwandan"},
    {code: "155", textValue: "Saint Lucian"},
    {code: "156", textValue: "Salvadoran"},
    {code: "157", textValue: "Samoan"},
    {code: "158", textValue: "San Marinese"},
    {code: "159", textValue: "Sao Tomean"},
    {code: "160", textValue: "Saudi"},
    {code: "161", textValue: "Scottish"},
    {code: "162", textValue: "Senegalese"},
    {code: "163", textValue: "Serbian"},
    {code: "164", textValue: "Seychellois"},
    {code: "165", textValue: "Sierra Leonean"},
    {code: "299", textValue: "Singaporean"},
    {code: "166", textValue: "Slovakian"},
    {code: "167", textValue: "Slovenian"},
    {code: "168", textValue: "Solomon Islander"},
    {code: "169", textValue: "Somali"},
    {code: "170", textValue: "South African"},
    {code: "171", textValue: "South Korean"},
    {code: "172", textValue: "Spanish"},
    {code: "173", textValue: "Sri Lankan"},
    {code: "174", textValue: "Sudanese"},
    {code: "175", textValue: "Surinamer"},
    {code: "176", textValue: "Swazi"},
    {code: "177", textValue: "Swedish"},
    {code: "178", textValue: "Swiss"},
    {code: "179", textValue: "Syrian"},
    {code: "180", textValue: "Taiwanese"},
    {code: "181", textValue: "Tajik"},
    {code: "182", textValue: "Tanzanian"},
    {code: "183", textValue: "Thai"},
    {code: "184", textValue: "Togolese"},
    {code: "185", textValue: "Tongan"},
    {code: "186", textValue: "Trinidadian or Tobagonian"},
    {code: "187", textValue: "Tunisian"},
    {code: "188", textValue: "Turkish"},
    {code: "189", textValue: "Tuvaluan"},
    {code: "190", textValue: "Ugandan"},
    {code: "191", textValue: "Ukrainian"},
    {code: "192", textValue: "Uruguayan"},
    {code: "193", textValue: "Uzbekistani"},
    {code: "194", textValue: "Venezuelan"},
    {code: "195", textValue: "Vietnamese"},
    {code: "197", textValue: "Welsh"},
    {code: "198", textValue: "Yemenite"},
    {code: "199", textValue: "Zambian"},
    {code: "200", textValue: "Zimbabwean"}
  ]
}

module.exports.countries = {
  codeTableId :   "Country",
  codeTableDescription: "List of countries",
  codeTableData: [

    {code: "1", textValue: "Andorra "},
    {code: "2", textValue: "Angola "},
    {code: "3", textValue: "Anguilla "},
    {code: "4", textValue: "Antigua & Barbuda "},
    {code: "5", textValue: "Austria "},
    {code: "6", textValue: "Bahamas, The "},
    {code: "7", textValue: "Bangladesh "},
    {code: "8", textValue: "Barbados "},
    {code: "9", textValue: "Belarus "},
    {code: "10", textValue: "Belgium "},
    {code: "11", textValue: "Belize "},
    {code: "12", textValue: "Benin "},
    {code: "13", textValue: "Bermuda "},
    {code: "14", textValue: "Bhutan "},
    {code: "15", textValue: "Brazil "},
    {code: "16", textValue: "British Virgin Is. "},
    {code: "17", textValue: "Brunei "},
    {code: "18", textValue: "Bulgaria "},
    {code: "19", textValue: "Burkina Faso "},
    {code: "20", textValue: "Burma "},
    {code: "21", textValue: "Burundi "},
    {code: "22", textValue: "Cambodia "},
    {code: "23", textValue: "Cameroon "},
    {code: "24", textValue: "Canada "},
    {code: "25", textValue: "Cayman Islands "},
    {code: "26", textValue: "Central African Rep. "},
    {code: "27", textValue: "Chad "},
    {code: "28", textValue: "Chile "},
    {code: "29", textValue: "China "},
    {code: "30", textValue: "Colombia "},
    {code: "31", textValue: "Comoros "},
    {code: "32", textValue: "Congo, Dem. Rep. "},
    {code: "33", textValue: "Cook Islands "},
    {code: "34", textValue: "Czech Republic "},
    {code: "35", textValue: "Denmark "},
    {code: "36", textValue: "Djibouti "},
    {code: "37", textValue: "Dominica "},
    {code: "38", textValue: "Dominican Republic "},
    {code: "39", textValue: "East Timor "},
    {code: "40", textValue: "Ecuador "},
    {code: "41", textValue: "Egypt "},
    {code: "42", textValue: "El Salvador "},
    {code: "43", textValue: "Equatorial Guinea "},
    {code: "44", textValue: "Eritrea "},
    {code: "45", textValue: "Estonia "},
    {code: "46", textValue: "Ethiopia "},
    {code: "47", textValue: "Faroe Islands "},
    {code: "48", textValue: "Fiji "},
    {code: "49", textValue: "Finland "},
    {code: "50", textValue: "France "},
    {code: "51", textValue: "French Guiana "},
    {code: "52", textValue: "French Polynesia "},
    {code: "53", textValue: "Gabon "},
    {code: "54", textValue: "Gambia, The "},
    {code: "55", textValue: "Gaza Strip "},
    {code: "56", textValue: "Georgia "},
    {code: "57", textValue: "Germany "},
    {code: "58", textValue: "Ghana "},
    {code: "59", textValue: "Gibraltar "},
    {code: "60", textValue: "Greece "},
    {code: "61", textValue: "Greenland "},
    {code: "62", textValue: "Grenada "},
    {code: "63", textValue: "Guadeloupe "},
    {code: "64", textValue: "Guam "},
    {code: "65", textValue: "Guatemala "},
    {code: "66", textValue: "Guernsey "},
    {code: "67", textValue: "Guinea "},
    {code: "68", textValue: "Guinea-Bissau "},
    {code: "69", textValue: "Guyana "},
    {code: "70", textValue: "Haiti "},
    {code: "71", textValue: "Honduras "},
    {code: "72", textValue: "Hong Kong "},
    {code: "73", textValue: "Hungary "},
    {code: "74", textValue: "Iceland "},
    {code: "75", textValue: "India "},
    {code: "76", textValue: "Indonesia "},
    {code: "77", textValue: "Iran "},
    {code: "78", textValue: "Iraq "},
    {code: "79", textValue: "Ireland "},
    {code: "80", textValue: "Isle of Man "},
    {code: "81", textValue: "Israel "},
    {code: "82", textValue: "Italy "},
    {code: "83", textValue: "Jamaica "},
    {code: "84", textValue: "Japan "},
    {code: "85", textValue: "Jersey "},
    {code: "86", textValue: "Jordan "},
    {code: "87", textValue: "Kazakhstan "},
    {code: "88", textValue: "Kenya "},
    {code: "89", textValue: "Kiribati "},
    {code: "90", textValue: "Korea, North "},
    {code: "91", textValue: "Korea, South "},
    {code: "92", textValue: "Kuwait "},
    {code: "93", textValue: "Kyrgyzstan "},
    {code: "94", textValue: "Laos "},
    {code: "95", textValue: "Latvia "},
    {code: "96", textValue: "Lebanon "},
    {code: "97", textValue: "Lesotho "},
    {code: "98", textValue: "Liberia "},
    {code: "99", textValue: "Libya "},
    {code: "100", textValue: "Liechtenstein "},
    {code: "101", textValue: "Lithuania "},
    {code: "102", textValue: "Luxembourg "},
    {code: "103", textValue: "Macau "},
    {code: "104", textValue: "Macedonia "},
    {code: "105", textValue: "Madagascar "},
    {code: "106", textValue: "Malawi "},
    {code: "107", textValue: "Malaysia "},
    {code: "108", textValue: "Maldives "},
    {code: "109", textValue: "Mali "},
    {code: "110", textValue: "Malta "},
    {code: "111", textValue: "Marshall Islands "},
    {code: "112", textValue: "Martinique "},
    {code: "113", textValue: "Mauritania "},
    {code: "114", textValue: "Mauritius "},
    {code: "115", textValue: "Mayotte "},
    {code: "116", textValue: "Mexico "},
    {code: "117", textValue: "Micronesia, Fed. St. "},
    {code: "118", textValue: "Moldova "},
    {code: "119", textValue: "Monaco "},
    {code: "120", textValue: "Mongolia "},
    {code: "121", textValue: "Montserrat "},
    {code: "122", textValue: "Morocco "},
    {code: "123", textValue: "Mozambique "},
    {code: "134", textValue: "N. Mariana Islands "},
    {code: "124", textValue: "Namibia "},
    {code: "125", textValue: "Nauru "},
    {code: "126", textValue: "Nepal "},
    {code: "127", textValue: "Netherlands "},
    {code: "128", textValue: "Netherlands Antilles "},
    {code: "129", textValue: "New Caledonia "},
    {code: "130", textValue: "New Zealand "},
    {code: "131", textValue: "Nicaragua "},
    {code: "132", textValue: "Niger "},
    {code: "133", textValue: "Nigeria "},
    {code: "135", textValue: "Norway "},
    {code: "136", textValue: "Oman "},
    {code: "137", textValue: "Pakistan "},
    {code: "138", textValue: "Palau "},
    {code: "139", textValue: "Panama "},
    {code: "140", textValue: "Papua New Guinea "},
    {code: "141", textValue: "Paraguay "},
    {code: "142", textValue: "Peru "},
    {code: "143", textValue: "Philippines "},
    {code: "144", textValue: "Poland "},
    {code: "145", textValue: "Portugal "},
    {code: "146", textValue: "Puerto Rico "},
    {code: "147", textValue: "Qatar "},
    {code: "148", textValue: "Reunion "},
    {code: "149", textValue: "Romania "},
    {code: "150", textValue: "Russia "},
    {code: "151", textValue: "Rwanda "},
    {code: "152", textValue: "Saint Helena "},
    {code: "153", textValue: "Saint Kitts & Nevis "},
    {code: "154", textValue: "Saint Lucia "},
    {code: "156", textValue: "Saint Vincent and the Grenadines "},
    {code: "157", textValue: "Samoa "},
    {code: "158", textValue: "San Marino "},
    {code: "159", textValue: "Sao Tome & Principe "},
    {code: "160", textValue: "Saudi Arabia "},
    {code: "161", textValue: "Senegal "},
    {code: "162", textValue: "Serbia "},
    {code: "163", textValue: "Seychelles "},
    {code: "164", textValue: "Sierra Leone "},
    {code: "165", textValue: "Singapore "},
    {code: "166", textValue: "Slovakia "},
    {code: "167", textValue: "Slovenia "},
    {code: "168", textValue: "Solomon Islands "},
    {code: "169", textValue: "Somalia "},
    {code: "170", textValue: "South Africa "},
    {code: "171", textValue: "Spain "},
    {code: "172", textValue: "Sri Lanka "},
    {code: "155", textValue: "St Pierre & Miquelon "},
    {code: "173", textValue: "Sudan "},
    {code: "174", textValue: "Suriname "},
    {code: "175", textValue: "Swaziland "},
    {code: "176", textValue: "Sweden "},
    {code: "177", textValue: "Switzerland "},
    {code: "178", textValue: "Syria "},
    {code: "179", textValue: "Taiwan "},
    {code: "180", textValue: "Tajikistan "},
    {code: "181", textValue: "Tanzania "},
    {code: "182", textValue: "Thailand "},
    {code: "183", textValue: "Togo "},
    {code: "184", textValue: "Tonga "},
    {code: "185", textValue: "Trinidad & Tobago "},
    {code: "186", textValue: "Tunisia "},
    {code: "187", textValue: "Turkey "},
    {code: "188", textValue: "Turkmenistan "},
    {code: "189", textValue: "Turks & Caicos Is "},
    {code: "190", textValue: "Tuvalu "},
    {code: "191", textValue: "Uganda "},
    {code: "192", textValue: "Ukraine "},
    {code: "193", textValue: "United Arab Emirates "},
    {code: "194", textValue: "United Kingdom "},
    {code: "195", textValue: "United States "},
    {code: "196", textValue: "Uruguay "},
    {code: "197", textValue: "Uzbekistan "},
    {code: "198", textValue: "Vanuatu "},
    {code: "199", textValue: "Venezuela "},
    {code: "200", textValue: "Vietnam "},
    {code: "201", textValue: "Virgin Islands "},
    {code: "202", textValue: "Wallis and Futuna "},
    {code: "203", textValue: "West Bank "},
    {code: "204", textValue: "Western Sahara "},
    {code: "205", textValue: "Yemen "},
    {code: "206", textValue: "Zambia "},
    {code: "207", textValue: "Zimbabwe "},
  ]
}

module.exports.states = {
  codeTableId :   "State",
  codeTableDescription: "List of states in Malaysia",
  codeTableData: [
    {code: "J" , textValue: "Johor"},
    {code: "K" , textValue: "Kedah"},
    {code: "D" , textValue: "Kelantan"},
    {code: "W" , textValue: "Kuala Lumpur"},
    {code: "O" , textValue: "Labuan"},
    {code: "M" , textValue: "Melaka"},
    {code: "N" , textValue: "Negeri Sembilan"},
    {code: "C" , textValue: "Pahang"},
    {code: "A" , textValue: "Perak"},
    {code: "R" , textValue: "Perlis"},
    {code: "P" , textValue: "Pulau Pinang"},
    {code: "S" , textValue: "Sabah"},
    {code: "Q" , textValue: "Sarawak"},
    {code: "B" , textValue: "Selangor"},
    {code: "T" , textValue: "Terengganu"},
  ]
}
